### ISSUE TITLE
Pass `request` around more, rather than things just derived from it

### ISSUE THREAD

**Issue by ababic** [rkhleics/wagtailmenus#106]
This is something I've found myself a little frustrated by in the past, and something that was prompted again by #105.

Currently, in all the places that it's easy to override behaviour (e.g. on various model methods), none of those methods take a HttpRequest object for the current request, so the potential for overriding functionality is a little bit stifled (you can't do anything based on the currently logged-in user, for example). Rather than passing around a bunch of stuff derived from the request between functions, we could just pass the HttpRequest itself around instead, and reduce the number of arguments being passed around.

**Comment by pyMan** [comment]
What about [crequest](https://pypi.python.org/pypi/django-crequest)?

**Comment by ababic** [comment]
@pyMan That link may help people wanting to access the current request in more places, so thanks for that. But, I wouldn't want to force users to install other dependencies or introduce extra steps to the setup if I can avoid it. Also, I think having the functions pass the right variables around is important for code readability.
