### ISSUE TITLE
Wagtail 1.8 support 

### ISSUE THREAD

**Issue by frague59** [rkhleics/wagtailmenus#113]
Thanks for this awesome menu !

I'm using Wagtail 1.8, and wagtailmenus works perfectly on dev (with wagtailmenus imported from githubl), but when I try to use it in prod, installing with pip, it tries to backpedal wagtail to 1.7.

**Comment by ababic** [comment]
Hey @frague59 Could you share your production requirements list here, so I can get a better understanding of what's going on?

Also, are you using the master branch of wagtailmenus to develop locally, or a stable branch?

**Comment by frague59** [comment]
Hi, 
I'm using the 2.2.1 package from pypi, it tries to install  the 1.7 release of wagtail.
I'm using the stable/2.2.x branch locally too. 

My problem is that when i :
```sh
# pip install wagtailmenus --upgrade
```
pip starts to install wagtail 1.7, I'm currently using 1.9 release.

**Comment by ababic** [comment]
Hi @frague59,

So, do you have an actual `requirements.txt` file or something where you define these things within your project? I feel like this is something you could easily control with something like:

```
wagtail>=1.9,<1.10
wagtailmenus>=2.2,<2.3
```

And then running `pip install -r requirements.txt --upgrade` would install everything you need for a project. In the above example, the wagtail version in your requirements file should override the dependency in wagtailmenus, so you wouldn't have any problems.
