### ISSUE TITLE
Migration issue

### ISSUE THREAD

**Issue by robmoorman** [rkhleics/wagtailmenus#119]
Version 2.2.2 with Wagtail version 1.9, clean install (running migrations on postgres database):

``CommandError: Conflicting migrations detected; multiple leaf nodes in the migration graph: (0021_auto_20170106_2352, 0018_auto_20161124_1107 in wagtailmenus).
To fix them run 'python manage.py makemigrations --merge'``

**Comment by ababic** [comment]
Hey @robmoorman. Thank you for raising :)

This is very weird, because 2.2 doesn't have a `0018_auto_20161124_1107` migration - only a `0018_auto_20161204_2043` one. What happens if you `pip uninstall wagtailmenus`, then install it again?

**Comment by robmoorman** [comment]
Ok caused by updating indeed. Strange. Issue doesn't pop up anymore! Thanks @ababic .
