### ISSUE TITLE
Error not visible when missing both link page and link url

### ISSUE THREAD

**Issue by pyMan** [rkhleics/wagtailmenus#123]
Django 1.11
Wagtail 1.10
Wagtailmenus 2.2.2

If both link to a page and link to a url are missing a general error si given to the user, but the real reason doesn't come up.

The missing error is, generated by `models.menuitems.AbstractMenuItem.clean`:
```
raise ValidationError(_(
                "You cannot link to both a page and URL. Please review your "
                "link and clear any unwanted values."
            ))
```

**Comment by ababic** [comment]
Hi @pyMan. Thank you for raising.

This is certainly a valid issue, but it's really something that needs to be tackled from the Wagtail side, as it's the views there that still don't display non-field errors consistently. Some progress has been made in the following PR https://github.com/wagtail/wagtail/pull/3440, but the same changes haven't yet made it through to the contrib.modeladmin app yet. as described in https://github.com/wagtail/wagtail/issues/3441

Also, as a sidenote, wagtailmenus doesn't yet officially support Wagtail version 1.10 or Django 1.11. That's something I intend to work on soon.
