### ISSUE TITLE
Submenu items creation

### ISSUE THREAD

**Issue by Brandhor** [rkhleics/wagtailmenus#129]
is it possible to create submenu items from the admin interface? for example if I want to add an external link in a sub menu, do I have to to use modify_submenu_items or is there another way?

**Comment by ababic** [comment]
Hi @Brandhor. Using `modify_submenu_items` would be the only way to do that in python. Wagtail doesn't provide any way to allow 'inlines within inlines' in their CMS, which is the main blocker for such functionality.

**Comment by ababic** [comment]
A bit messy, but you could always add a simple 'External link' page type and add an actual `Page` of that type into to the tree in the relevant place?

**Comment by Brandhor** [comment]
yeah I might do that, thanks
