### ISSUE TITLE
Attribute Error when rendering a preview from the admin

### ISSUE THREAD

**Issue by Adrian-Turjak** [rkhleics/wagtailmenus#132]
```
Error during template rendering:
...
File "/home/adrian/projects/minedash/.venv/local/lib/python2.7/site-packages/django/template/library.py", line 203, in render
    output = self.func(*resolved_args, **resolved_kwargs)
  File "/home/adrian/projects/minedash/.venv/local/lib/python2.7/site-packages/wagtailmenus/templatetags/menu_tags.py", line 31, in main_menu
    context, guess_tree_position=True)
  File "/home/adrian/projects/minedash/.venv/local/lib/python2.7/site-packages/wagtailmenus/utils/misc.py", line 17, in get_attrs_from_context
    current_page = wagtailmenus_vals.get('current_page')
  File "/home/adrian/projects/minedash/.venv/local/lib/python2.7/site-packages/django/utils/functional.py", line 238, in inner
    self._setup()
  File "/home/adrian/projects/minedash/.venv/local/lib/python2.7/site-packages/django/utils/functional.py", line 385, in _setup
    self._wrapped = self._setupfunc()
File "/home/adrian/projects/minedash/.venv/local/lib/python2.7/site-packages/wagtailmenus/context_processors.py", line 16, in _get_value_dict
    site = request.site
AttributeError: 'WSGIRequest' object has no attribute 'site'
```

Error occurs when it tries to process:  {% main_menu %}

Page itself is entirely visible once live, just the preview that is dying. Not entirely sure what could be causing it :(

**Comment by Adrian-Turjak** [comment]
NVM, just looked at your code and the commit history.

You fixed it. When will you push a new package to pypi?

**Comment by ababic** [comment]
Hi @Adrian-Turjak. There's just one outstanding thing that I'd like to resolve before I package things for `2.3`, and that's #131. That should be reasonably simple, but I can't provide dates for releases because I have too many other commitments currently. Hopefully it'll be some time in the next few weeks.

**Comment by ababic** [comment]
Hi @Adrian-Turjak. Just a thought. The error you posted above would only be thrown if Wagtail's `SiteMiddleware` isn't doing it's job properly. Whether previewing or viewing a live page, I'd expect the behaviour of `SiteMiddleware` to be consistent. You may want to raise a bug with Wagtail if it is not.

**Comment by Adrian-Turjak** [comment]
*sigh* I just did some testing. Appears to be user error, entirely unrelated to your library. Deployed the wagtail demo site, played with a few things, and found the issue.

The preview fails when the site hostname doesn't match the actual host the site is being accessed on. Viewing the site itself directly works and it seems to use the default site, but the preview fails, and the error isn't helpful. In my dev environment I must have mistakenly renamed the hostname and not realised the issue.

Not sure if really a bug or not, but am closing this. Thanks! Wouldn't have found the issue if you hadn't pointed me in the right direction. :P

**Comment by ababic** [comment]
No problem :) I think this same thing has tripped me up in the past, and possibly even might have been the cause of the original issue that caused me to make wagtailmenus less dependent  `request.site` always being set :P
