### ISSUE TITLE
Missed *.mo files for LT and RU locales, missed ugettext_lazy call in wagtail_hooks.py

### ISSUE THREAD

**Issue by einsfr** [rkhleics/wagtailmenus#135]
wagtail_hooks.py:107
    handle_formatted.short_description = 'handle'
must be:
    handle_formatted.short_description = _('handle')

**Comment by ababic** [comment]
Hey @einsfr,

Thank you for raising. All transifex seems to give me when I download/pull translations are the `.po` files for each language. So that I know for future, where do I get the `.mo` files from? (Sorry, I'm pretty new to all this translation stuff!)

**Comment by einsfr** [comment]
You'll need a `msgfmt` programm, which is a part of gettext utilities. Usage guide: https://www.gnu.org/software/gettext/manual/gettext.html#msgfmt-Invocation

In short: msgfmt --check-format -o django.mo django.po
