### ISSUE TITLE
Make wagtailmenus Python 3 compatible

### ISSUE THREAD

**Issue by ababic** [rkhleics/wagtailmenus#14]

**Comment by hop** [comment]
What is the actual problem? The test suite seems to run fine.

**Comment by ababic** [comment]
Hi @hop! I've raised it as an issue here because I simply haven't ever tested in a Python 3 environment or even thought to until recently (We use 2.7 internally, and that's all I've ever ran/developed/tested in), and want to be absolutely sure I can give things that stamp of approval. 

I'm determined to manage this project responsibly and be up front with developers about what is tested and what isn't, and what is officially supported or not etc. It's essential in helping them make informed decisions about what to use for their projects. 

If you're saying that everything is running/testing fine in a python 3 environment though, that's certainly good news :)

**Comment by hop** [comment]
I cannot speak to "all", but I successfully configured a main menu and added it to a template.

**Comment by ababic** [comment]
@hop Thanks for the info. It turns out 3.4 and 3.5 compatibility wasn't an issue at all (confirmed by automated travis CI tests in my fork). Have now merged my pull into the master. I don't want to create a new pypi release just yet, but since compatibility isn't actually a problem, there's no urgent need for a new release.
