### ISSUE TITLE
[Enhancement] Flat Menu Choices settings value

### ISSUE THREAD

**Issue by Adrian-Turjak** [rkhleics/wagtailmenus#160]
A lot of the time the flat menu handles for your site are predefined and normally hardcoded in your templates, and since there is no easy way to have the handles as defined in your templates as options in the admin, hardcoding those options is a good idea. Saves your users having to remember the menu handles.

So a useful feature might be a setting which provides some choices for the flatmenu handle, and having the admin widget offer those. This would mean there is less chance of a flatmenu being created that has a handle that will never render.

I've done this by making a custom flatmenu as follows: 

```
flat_menu_choices = [
    ('header-menu', 'Header Menu (signup, login, etc)'),
    ('footer-menu', 'Footer Menu (contact us, twitter, etc)'),
    ('footer-links', 'Footer Links (Privacy notice, etc)'),
]


class CustomFlatMenu(AbstractFlatMenu):
    """A custom FlatMenu for the Catalyst Cloud site

    Mostly just to hardcode the options as used in the base.html file.
    """
    handle = models.SlugField(
        verbose_name=_('handle'),
        max_length=100,
        choices=flat_menu_choices,
        help_text=_(
            "Used to reference this menu in templates etc."
        )
    )
```

But having this as a setting could prove useful and in a case where you don't need or want a custom FlatMenuItem, will save you having to also make one just to override the handle choices for FlatMenu. For my project I did want a custom FlatMenuItem as well, but for most people that likely won't be the case.

**Comment by ababic** [comment]
Hi @Adrian-Turjak. This already exists. See http://wagtailmenus.readthedocs.io/en/latest/settings_reference.html#wagtailmenus-flat-menus-handle-choices

**Comment by Adrian-Turjak** [comment]
*faceplam*

Sorry! Totally missed it in the docs. Will update my code appropriately then since I don't need a custom flatmenu then, just items. :P
