### ISSUE TITLE
Accessing specific page content in menu items?

### ISSUE THREAD

**Issue by jtebert** [rkhleics/wagtailmenus#172]
Is there a way to access model fields of specific pages in a custom template? For example, I have an icon for each page that I want to display with the page's item in the menu. From my reading of the documentation, I thought that if I set use_specific=3, I would then be able to retrieve content specific to the page type. However, this appears to be the case:

```
{% for item in menu_items %}
    {{ item.text}}
    {{ item.additional_field }}
{% endfor %}
```

where `additional_field` is a field oe my CustomPage type.

Have I misinterpreted what `use_specific` allows me to do? And if so, is there an alternative way to access this content?

**Comment by ababic** [comment]
Hi @jtebert. If your template is for a main menu or flat menu, `menu_items` will be a list of MenuItem instances, and the page is available as `item.link_page`, so you can do `{{ item.link_page.addition_field }}`. 

In all other templates,  `menu_items` is a list of pages, so you can access page fields from the item itself, like in your original example.
