### ISSUE TITLE
What about to create submenus manually?

### ISSUE THREAD

**Issue by moreplavec** [rkhleics/wagtailmenus#179]
Is there going to be function to create sub-menu manually? Now i can create top level manually and than i need to generate via customized templates. But what if i need to link pages across top level, link hash links, external websites aso... or is it possible now?

**Comment by ababic** [comment]
Hi @moreplavec.

I'm afraid I'm not quite sure what you mean by 'manually' here. Sub menus are powered entirely by the page tree (they are only generated for page links), and so aren't defined in the CMS separately.

Can you explain some more about what you're trying to achieve? I might be able to point you in the right direction.

**Comment by moreplavec** [comment]
For example, i have such tree:

- Home
- Products
-- Product XX (has category 1)
-- Product ZZ (has category 2)
- Services
-- anchor link in page #service1
-- anchor link in page #service2
- Testimonials
- Contact


But for menu i need:

- Home
- Products
-- Category 1
-- Category 2
-- Eshop (link to another website)
- Services
-- Service 1
-- Service 2
-Testimonials
-- Testimonial category 1
-- Testimonial category 2
- Contact

so, is there any way how to create this manually? Or any other way?

**Comment by ababic** [comment]
Hi @moreplavec.

There are currently two options you might like to explore:

Page models using the `MenuPageMixin` are capable of altering their sub-menu items when they appear in menus. So, you could use that with for your 'Products', 'Services', and 'Testimonials' page types and override 'modify_submenu_items()' to add the items you need. See:
http://wagtailmenus.readthedocs.io/en/stable/menupage.html

Or you could create a page type using `AbstractLinkPage`, and add the links as pages to your page tree. See: http://wagtailmenus.readthedocs.io/en/stable/abstractlinkpage.html

There will also be some hooks you can use soon that will allow you to modify menu items for any menu (they should be available in the next release), See: http://wagtailmenus.readthedocs.io/en/latest/advanced_topics/hooks.html#hooks-for-modifying-menu-items-before-rendering

**Comment by ababic** [comment]
@moreplavec 

You can happily mix both of those approaches too. I would think links like 'Eshop' would fit the `AbstractLinkPage` approach more nicely. While, the `MenuPageMixin` approach is useful if you want to add many links, or links dependent on data in other models etc.

**Comment by viirak** [comment]
How about a link to Snippets (ex: ArticleCategory page)?
- Category 1
  - Category 1.1
  - Category 1.2

**Comment by ababic** [comment]
Hi @viirak Wagtailmenus is never going to be something that will facilitate showing any kind of data in any kind of structure. It exists to solve the most common menu needs and do a semi-decent job of them. Without knowing far more details about what you're wanting to achieve, it's difficult to know what suggest - But, it sound's like just adding categories to the context and rendering them with your own template (or inside a menu template) could be your best bet.

**Comment by moreplavec** [comment]
AbstractLinkPage looks good to me, until there will be (i hope it will) something in admin areal to use. Nice doc are reading, but i prefer real life examples. Are there any demo uses for some scenarios?

**Comment by ababic** [comment]
Hi @moreplavec. I just wanted to be clear here for anyone coming to this thread... this app wont ever offer the ability to inject arbitrary data into menus, or manage completely custom, multiple level menus via the admin interface. To offer those kind of features, you'd take an entirely different approach to development - and the solution would likely be completely at odds with much of the existing codebase. It would have to be a new project/app - bending this app to fit would just result in confused / conflicted mess.

I agree the documentation would benefit from more examples. I'd gladly accept any contributions there!

**Comment by viirak** [comment]
@ababic just like AbstractLinkPage, but for snippets. 

class PostCategoryLinkPage(Page):
    category = models.ForeignKey(
        'post.PostCategory',
        null=False,
        blank=False,
        on_delete=models.PROTECT,
        related_name='+'
    )

    content_panels = Page.content_panels + [
        SnippetChooserPanel('category'),
    ]

**Comment by ababic** [comment]
Hi @viirak, 

I see what you're going for there. I can't see any way of making something suitably generic enough that it would be useful in use cases such as this. The very fact that the model needs a ForeignKey to a specific model is is limiting. I also don't know how to ascertain a useful 'URL' to use from the selected thing. The implementation would almost entirely always be custom.

Also, as I've mentioned before - Is duplicating some things to create some kind of structure elsewhere really the best approach for solving the problem?

Do you really want to create another of these pages every time you create a category that you want to appear in the navigation?

What happens when the category is deleted?

Surely it would make more sense to add a 'show_in_menus' BooleanField to the PostCategory model, and have those objects dynamically output as menu items somewhere?
