### ISSUE TITLE
Breaks Django Debug Toolbar: get_version() missing 1 required positional argument: 'version'

### ISSUE THREAD

**Issue by FlipperPA** [rkhleics/wagtailmenus#184]
I'm running into an issue with Wagtail menus. When I install and add to `INSTALLED_APPS`, I get the follow error when I go to either the Wagtail or Django admins:

    get_version() missing 1 required positional argument: 'version'

I've tried both `2.4.1` and `2.5rc1`. It seems to be a conflict with Django Debug Toolbar. Without `wagtailmenus` everything works. Here's the pertinent info:

    Django==1.11.6
    wagtail==1.12.2
    django-debug-toolbar=1.8

And the stack trace:

    Request Method: GET
    Request URL: http://vagrant.wharton.upenn.edu:8000/admin/login/?next=/admin/

    Django Version: 1.11.6
    Python Version: 3.5.4
    Installed Applications:
    ['django.contrib.admin',
     'django.contrib.auth',
     'django.contrib.contenttypes',
     'django.contrib.sessions',
     'django.contrib.messages',
     'django.contrib.sites',
     'django.contrib.staticfiles',
     'wagtail.wagtailcore',
     'wagtail.wagtailadmin',
     'wagtail.wagtaildocs',
     'wagtail.wagtailsnippets',
     'wagtail.wagtailusers',
     'wagtail.wagtailimages',
     'wagtail.wagtailembeds',
     'wagtail.wagtailsearch',
     'wagtail.wagtailsites',
     'wagtail.wagtailredirects',
     'wagtail.wagtailforms',
     'wagtail.contrib.modeladmin',
     'wagtail.contrib.postgres_search',
     'wagtail.contrib.table_block',
     'wagtailcodeblock',
     'wagtailcontentstream',
     'wagtailfontawesome',
     'wagtailerrorpages',
     'wagtailmenus',
     'taggit',
     'modelcluster',
     'bootstrap4',
     'meetings',
     'meeting_import',
     'recurrence',
     'cms',
     'events',
     'newsletter',
     'debug_toolbar',
     'django_extensions',
     'template_debug']
    Installed Middleware:
    ['django.middleware.security.SecurityMiddleware',
     'django.contrib.sessions.middleware.SessionMiddleware',
     'django.middleware.common.CommonMiddleware',
     'django.middleware.csrf.CsrfViewMiddleware',
     'django.contrib.auth.middleware.AuthenticationMiddleware',
     'django.contrib.messages.middleware.MessageMiddleware',
     'django.middleware.clickjacking.XFrameOptionsMiddleware',
     'wagtail.wagtailcore.middleware.SiteMiddleware',
     'wagtail.wagtailredirects.middleware.RedirectMiddleware',
     'debug_toolbar.middleware.DebugToolbarMiddleware']

    Traceback:

    File "/home/vagrant/.virtualenvs/sepia/lib/python3.5/site-packages/django/core/handlers/exception.py" in inner
      41.             response = get_response(request)

    File "/home/vagrant/.virtualenvs/sepia/lib/python3.5/site-packages/django/utils/deprecation.py" in __call__
      142.             response = self.process_response(request, response)

    File "/home/vagrant/.virtualenvs/sepia/lib/python3.5/site-packages/debug_toolbar/middleware.py" in process_response
      132.                 panel.generate_stats(request, response)

    File "/home/vagrant/.virtualenvs/sepia/lib/python3.5/site-packages/debug_toolbar/panels/versions.py" in generate_stats
      29.         versions += list(self.gen_app_versions())

    File "/home/vagrant/.virtualenvs/sepia/lib/python3.5/site-packages/debug_toolbar/panels/versions.py" in gen_app_versions
      39.             version = self.get_app_version(app)

    File "/home/vagrant/.virtualenvs/sepia/lib/python3.5/site-packages/debug_toolbar/panels/versions.py" in get_app_version
      47.                 version = get_version()

    Exception Type: TypeError at /admin/login/
    Exception Value: get_version() missing 1 required positional argument: 'version'

Thanks for all your efforts - any ideas on a work around would be appreciated!

**Comment by ababic** [comment]
Closing this as it's a duplicate of #161 and #115. For workaround, see https://github.com/rkhleics/wagtailmenus/issues/161#issuecomment-330653556

**Comment by FlipperPA** [comment]
My apologies for not being more thorough, @ababic - I'm normally good about that!

**Comment by ababic** [comment]
No problem @FlipperPA! Hope you find the app useful. If you're trying out `2.5rc1`, please let me know if you have problems.
