### ISSUE TITLE
Adding a window target for the URL aka target="_blank"

### ISSUE THREAD

**Issue by mr-bo-jangles** [rkhleics/wagtailmenus#187]
As it stands we can add external links, but there is no way to specify that I'd like them to open in a new tab.

Our use case for this is having an external webapp that we link to from our menu bar. We want to be able to link to it and have the site remain open in a tab in the users browser.

**Comment by ababic** [comment]
Hi @mr-bo-jangles! A few possible solutions come to mind:

1. Use a custom menu template with a simple `{% if %}` block to conditionally output a `target` attribute
2. Add the `target` attribute using client-side javascript
3. Write a python method to conditionally additional a `target` attribute to each item, utilising the [`menus_modify_primed_menu_items`](http://wagtailmenus.readthedocs.io/en/latest/advanced_topics/hooks.html#menus-modify-primed-menu-items) hook, and make use of the attribute in a custom menu template
4. If you need to the `target` value to be editable in the CMS, consider creating your own menu item model (See: http://wagtailmenus.readthedocs.io/en/latest/advanced_topics/custom_menu_classes.html#using-custom-menu-classes-and-models)
