### ISSUE TITLE
Drop support for Python 2 & 3.3

### ISSUE THREAD

**Issue by ababic** [rkhleics/wagtailmenus#198]
Actions required:

- [x] Include a note in 2.6 release notes announcing that it will be the last version to support Python 2
- [x] Remove as much Python 2 specific code as possible
- [x] Remove Python 2 environment tests from tox configuration 
- [x] Update `python_requires` in setup.py to reflect supported versions

**Comment by hugovk** [comment]
Here's the pip installs for wagtailmenus from PyPI for the last month (via `pypinfo --percent --pip --markdown wagtailmenus pyversion`), showing no Python 2.6 and quite low 2.7 numbers, especially compared to 3.x, which is over 91%.

| python_version | percent | download_count |
| -------------- | ------: | -------------: |
| 3.5            |   46.6% |            346 |
| 3.6            |   39.2% |            291 |
| 2.7            |    8.6% |             64 |
| 3.4            |    5.4% |             40 |
| 3.7            |    0.1% |              1 |
| 3.3            |    0.1% |              1 |

**Comment by ababic** [comment]
@hugovk Thanks for sharing. It hadn't occurred to me check download figures, but that's good to know. With Django 2.0 out already and Wagtail 2.0 not far away, it just seems like the right time. They've already made the big/impactful decisions, so most developers in this space will be moving over to py3 soon if they haven't already. I'm mostly just excited about using the tidier 'super()' throughout :)

**Comment by hugovk** [comment]
Things will be much easier with just Python 3.4+!

Make sure to use python_requires in setup.py, which can be added already. 

https://stackoverflow.com/a/44660547/724176

**Comment by ababic** [comment]
Thanks, that's super helpful.

**Comment by ababic** [comment]
This has been implemented, but I'll keep this issue open until version 2.7 is released and out of the door.

**Comment by hnykda** [comment]
Hey. May I know when 2.7 is going to be release? We would like to bump django/wagtail to 2.0 and wagtailmenus are the only dependency which is stopping as from that. And it seems that both tickets from 2.7 milestone are done.

Thanks!

**Comment by ababic** [comment]
Hi @hnykda,

2.7 will be released very soon (in the next few days). If you don't want to wait, you include the github repo as a branch for now (master branch), and that should work.

**Comment by hnykda** [comment]
Hey. Thanks. Yeah, we know we can install from github, I was just curious when the next release is going to come.
