### ISSUE TITLE
Wagtail Menus not showing all menu items

### ISSUE THREAD

**Issue by kamalkataria** [rkhleics/wagtailmenus#207]
I am using wagtail cms for making my blog. So I have installed wagtail menus inside my django project. I followed the official documentation for creating a top level menu but it showing the single item which I created in wagtail admin.
`Settings.py

 INSTALLED_APPS = [
'bootstrap3',
'blog',
'home',
'search',

'wagtail.wagtailforms',
'wagtail.wagtailredirects',
'wagtail.wagtailembeds',
'wagtail.wagtailsites',
'wagtail.wagtailusers',
'wagtail.wagtailsnippets',
'wagtail.wagtaildocs',
'wagtail.wagtailimages',
'wagtail.wagtailsearch',
'wagtail.wagtailadmin',
'wagtail.wagtailcore',
'wagtail.contrib.modeladmin',  # Don't repeat if it's there already
'wagtailmenus',

'modelcluster',
'taggit',

'django.contrib.admin',
'django.contrib.auth',
'django.contrib.contenttypes',
'django.contrib.sessions',
'django.contrib.messages',
'django.contrib.staticfiles',
]`

`Middleware:

 MIDDLEWARE = [
'django.contrib.sessions.middleware.SessionMiddleware',
'django.middleware.common.CommonMiddleware',
'django.middleware.csrf.CsrfViewMiddleware',
'django.contrib.auth.middleware.AuthenticationMiddleware',
'django.contrib.messages.middleware.MessageMiddleware',
'django.middleware.clickjacking.XFrameOptionsMiddleware',
'django.middleware.security.SecurityMiddleware',

'wagtail.wagtailcore.middleware.SiteMiddleware',
'wagtail.wagtailredirects.middleware.RedirectMiddleware',
]

contextprocessors:

'context_processors': [
            'django.template.context_processors.debug',
            'django.template.context_processors.request',
            'django.contrib.auth.context_processors.auth',
            'django.contrib.messages.context_processors.messages',
            'wagtail.contrib.settings.context_processors.settings',
            'wagtailmenus.context_processors.wagtailmenus',
            'django.template.context_processors.i18n',
            'django.template.context_processors.media',
            'django.template.context_processors.static',
            'django.template.context_processors.tz',
        ],`

I included this code in base.html to include the mainmenu.

  ```
{% wagtailuserbar %}
  {% load menu_tags %}
  {% main_menu max_levels=3  show_multiple_levels=True apply_active_classes=True %}
```
Then I created 3 pages in admin and tried to link the menus.The main and the flat menu option is there for creating the menu.I used main menu and created some menu items using the pages I created but I am getting only Home menu which I created the first.The other menu items are not visible.

**Comment by ababic** [comment]
Hi @kamalkataria. It sounds like the other pages probably don't have a `show_in_menus` value of `True`. 

Try editing the pages in question and checking whether the “Show in menus” checkbox is checked (found under the “Promote” tab by default).

**Comment by kamalkataria** [comment]
Thankyou. It resolved the problem :)
