### ISSUE TITLE
Add support for Wagtail 2.0 and Django 2.0

### ISSUE THREAD

**Issue by ababic** [rkhleics/wagtailmenus#209]

**Comment by maschioalfonso** [comment]
Does anybody try to include Wagtail in a Django 2.0 project ? 
Any result or shared experience ?

**Comment by ababic** [comment]
@maschioalfonso Wagtail doesn't yet support Django 2. Support will be added in the next Wagtail release (2.0), which is currently in Beta and will be available soon.

**Comment by ababic** [comment]
Resolved by ddf6132
