### ISSUE TITLE
Ordering for Child Menus

### ISSUE THREAD

**Issue by casey-chow** [rkhleics/wagtailmenus#211]
Hi there! I've been using this for a hackathon site and it's been working great; I just wanted to ask if there was a way to specify the ordering for child menus. Is there a way to hack it with timestamps or something?

(If there are not plans to add it in the near future, I'd be happy to take a crack at implementing the feature!)

**Comment by ababic** [comment]
Hi @casey-chow. Apologies for the late response. I completely missed this somehow!

This sounds like an almost perfect use case for the [`menus_modify_raw_menu_items` hook](http://wagtailmenus.readthedocs.io/en/v2.6.0/advanced_topics/hooks.html#menus-modify-raw-menu-items), using the `original_menu_tag` kwarg to conditionally reorder the menu items before returning again. 

Probably something like this:

```
from wagtail.wagtailcore import hooks
from operator import attrgetter

@hooks.register('menus_modify_raw_menu_items')
def reorder_children_menu_items_by_timestamp(
    menu_items, original_menu_tag, current_level, **kwargs
):
    if original_menu_tag == 'children_menu' and current_level == 1:
        return sorted(menu_items, key=attrgetter('some_timestamp_field'), reverse=True)
    return menu_items
```

**Comment by ababic** [comment]
Hi @casey-chow. Was the above information any help to you?

**Comment by casey-chow** [comment]
It did, thanks! I was mostly looking for manual ordering--I didn't realize the [Explorer had this functionality already](http://docs.wagtail.io/en/v1.7/editor_manual/finding_your_way_around/the_explorer_page.html#the-explorer-page).
