### ISSUE TITLE
Upgrading 2.3 -> 2.6 menu_items

### ISSUE THREAD

**Issue by dwasyl** [rkhleics/wagtailmenus#225]
Hi there,

I am in the process of updating to the latest (well will be stuck at 2.6 for a while) from 2.3. Previously, the existence of `menu_items` in a template context meant the page had sub menu items. `menu_items` doesn't seem to be added to the context anymore and I couldn't dig up a note about what replaced it.

Any tips to get the current page's menu context? It's being used to display an in-page menu.

Cheers

**Comment by ababic** [comment]
I'm sorry @dwasyl, but I don't quite understand what is being asked for here. Which menu tag are you using, and what are you trying to access from where? Are you able to provide code samples?

**Comment by dwasyl** [comment]
Sure @ababic, in my template I'm displaying a section menu in template (so not as part of the menu bar) using `{% section_menu template=X %}`, when a page as sub-pages.

Currently, I check for it by using a simple `if` statement in the template:
```
{% if menu_items %}
{% section_menu template='sidebarmenu.html' %}
{% endif %}
```

In previous versions, whenever a page had sub-pages (or menu children), `menu_items` was populated, but not in `2.6`

**Comment by ababic** [comment]
Did this code actually ever work in a previous version or is it new? It looks like you were relying on a context leakage bug (where `menu_items` would actually be the menu items from whatever menu happend to have been rendered prior to this one).

The better approach here would be to just remove the if statement from around the `{% section_menu %} ` tag, and instead create a custom section_menu template that doesn't output anything unless there are menu items.

**Comment by dwasyl** [comment]
It worked like a charm in 2.3 (on Django 1.8/Wagtail 1.11). Makes sense though, realizing it wasn't supposed to be there I just changed around the templating code. Originally it was just there allow the same template to be used in two slightly similar spots, so instead I just created a second template..

Thanks!
