### ISSUE TITLE
Be more helpful when not serving a `Page` object

### ISSUE THREAD

**Issue by ababic** [rkhleics/wagtailmenus#23]
Internally, we've gotten quite used to writing apps to make them fit nicely into Wagtail's Page tree... so we're almost always serving a 'Page' object via wagtail's routing mechanism, which wagtailmenus plays very nicely with. We're also utilising Wagtail's [before_serve_page](http://docs.wagtail.io/en/v1.5.3/reference/hooks.html#before-serve-pagel) hook to add some helpful data to `request.META`, which we also use within the template tags.

In reality though, I think it's still very common for developers NOT to use the Page tree for additional apps in their projects (perhaps because they're using a third-party app that's too complicated to adapt, or because they're simply not keen on the idea of being tied to wagtail's routing mechanism). Whatever the reason, I think menu tags should do a better job of 'back-filling' when `self` isn't present in the context, or `CURRENT_SECTION_ROOT` and `CURRENT_PAGE_ANCESTOR_IDS` aren't set on `request.META`. The `section_menu` tag is the worst offender, as it fails to render anything unless `before_serve_page` has set `CURRENT_SECTION_ROOT` for it.

There's no reason we can't use `request.site` and `request.path` to attempt to find a 'current page', even if it means recursively stripping fragments from the URL to find a nearby ancestor. With this, we could at least try to find a 'section_root' page to make `section_menu` work, and we could get at least some nav items highlighting properly (by identifying a set of 'ancestor ids')

**Comment by ababic** [comment]
Fixed by #24

**Comment by dwasyl** [comment]
Quick question, @ababic will fix #24 make section menus work better when using RoutablePageMixin type of routing for pages?

**Comment by ababic** [comment]
Hi @dwasyl.

**Comment by ababic** [comment]
Hi @dwasyl. I think the `modify_submenu_items` method added the `MenuPage` in #20 is more likely to help you there. You could override that to add additional 'routes' as subpage links.

**Comment by ababic** [comment]
#24 Shouldn't really make much difference when actually serving a 'RoutablePageMixin' route, because generally you still supply `self` to the context, which will be the current page. And wagtail should still run 'before_serve_page', so `wagtailmenus.wagtailhooks.wagtailmenu_params_helper()` should still run and add details to the request to be picked up. 

I suppose it really depends on how you're doing things in your project. If you're bypassing all of that somehow, then I guess none of that data will be available - in which case #24 and #26 will help out.

**Comment by dwasyl** [comment]
Ah! That makes sense. I may have left out self when I first tried the RoutablePageMixins.
