### ISSUE TITLE
Widget media's ignored by wagtailmenus?

### ISSUE THREAD

**Issue by fpoulain** [rkhleics/wagtailmenus#250]
Hi,
Using django-fontawesome in wagtailmenu doesn't work for me, whereas it works as-is when I put it in base wagtail models. The admin form seems well builded but the js and css deps seems not included. Are widget's media ignored by wagtailmenus?

My code:
```python
from fontawesome.fields import IconField
from wagtailmenus.models import AbstractFlatMenuItem
from modelcluster.fields import ParentalKey
class HomeFlatMenuItem(AbstractFlatMenuItem):
    menu = ParentalKey( 'wagtailmenus.FlatMenu',
            on_delete=models.CASCADE,
            related_name="home_menu_items",
            )
    icone = IconField(
        verbose_name= 'Icone',
        max_length= 100,
        blank= True,
        help_text= "Icone du menu",
    )
    panels= AbstractFlatMenuItem.panels + [
            FieldPanel('icone')
            ]
```

**Comment by ababic** [comment]
Hi @fpoulain,

I think what you're observing here is a limitation of Wagtail, rather than something wagtailmenus is doing. In the past, I've found that you have to use the `widget` argument when defining a `FieldPanel` instance to get it to use a custom widget. 

I have a feeling this might work if you added `from fontawesome.widgets import IconWidget` to your imports, and updated your panels definition like so:

```
panels = AbstractFlatMenuItem.panels + [
    FieldPanel('icone', widget=IconWidget)
]
```

If that still doesn't work, let me know.

**Comment by ababic** [comment]
Hi @fpoulain, did you have an luck with the above approach?

**Comment by fpoulain** [comment]
Hi ababic,
Thanks for your answer. I didn't get time to try before tonight.

> I think what you're observing here is a limitation of Wagtail,

By the way:
* if I define my model with icone = IconField('Icone', blank= True) and I add FieldPanel('icone') to content_panels, it works with wagtail as expected.
* If I define it in a StreamBlock, it works with wagtail as expected.

So, my problem occurs only in when I use that field in a menu.

> I have a feeling this might work if you added from fontawesome.widgets import IconWidget to your imports

I tried before reporting the bug, and I retried this way tonight, and it didn't work.

**Comment by ababic** [comment]
Hi @fpoulain,

Okay, sorry to hear that didn't solve the problem. Does it work for you elsewhere in Wagtail if you use the field on a model included in an interface using `InlinePanel` (like menu items are)? I think that could make a difference.

Also, are you using wagtailmenus with https://github.com/wagtail/wagtail-condensedinlinepanel or without?

**Comment by ababic** [comment]
I've been trying this out locally, and it seems to be working fine for me when added to a custom menu item model, using just a standard `FieldPanel`:

On a custom main menu:

<img width="927" alt="screenshot 2018-06-13 at 22 06 17" src="https://user-images.githubusercontent.com/7779588/41378285-88980174-6f56-11e8-8709-5f9fdee2cc84.png">

And on a custom flat menu:

<img width="1116" alt="screenshot 2018-06-13 at 22 07 09" src="https://user-images.githubusercontent.com/7779588/41378296-94cec144-6f56-11e8-82d5-f10350b36e5d.png">

Do you see any javascript errors in your console or anything? Perhaps there's a conflict with something else your using?

**Comment by fpoulain** [comment]
> I've been trying this out locally, and it seems to be working fine for me when added to a custom menu item model, using just a standard FieldPanel.

Arf, very weird. It continue to not work here. Can you please post your code snippet ? I am using wagtail 2.0.1 and wagtailmenus 2.9 with python 3.5.

> Do you see any javascript errors in your console or anything?

No, the css and js links aren't added in the head. That's why I thought the menu class missed widget's media somewhere. Also, the select html widget is properly built, it only miss the css and js link.

> Perhaps there's a conflict with something else your using?

I have only very few deps and its a "toy" project to learn wagtail.

**Comment by ababic** [comment]
Hi @fpoulain,

I just followed the installation instructions from here:
https://github.com/redouane/django-fontawesome

Added an `IconField` (supplying no arguments, as shown in the project's README) to the `MultilingualMenuItem` model from:
https://github.com/rkhleics/wagtailmenus/blob/master/wagtailmenus/tests/models/menus.py#L25

Updated the `panels` attribute on the same model to include `FieldPanel('icon')`

Updated the development settings to:
```
WAGTAILMENUS_MAIN_MENU_MODEL = 'tests.CustomMainMenu'
WAGTAILMENUS_FLAT_MENU_MODEL = 'tests.CustomFlatMenu'
```

And the field rendered as show in the screenshots (using Wagtail 2.0 and latest dev version of wagtailmenus - which shouldn't matter, as there have been absolutely no UI/modeladmin changes for a good few versions)

**Comment by ababic** [comment]
Closing this for now, as am unable to replicate the issue.

**Comment by fpoulain** [comment]
Ok. I didn't found time to check it. I will recreate a from scratch project and try to understand why this don't work for me. Thanks for help.
