### ISSUE TITLE
Main-menu hrefs show up as "/"

### ISSUE THREAD

**Issue by SundialServices** [rkhleics/wagtailmenus#277]
Carefully following the instructions for "Managing main menus via the CMS," I created a menu associated with my home page – which is published, has a slug of "home," and which has "show in menus," and yet the `href="/"`.

The title of the page is "Too Cool"  But none of the other pages, with more-conventional names such as "Products," seem to work either.

I have entered no settings other than the defaults.  I simply selected the page I wanted to link to, and hit "Save."

**Comment by ababic** [comment]
Hi @SundialServices. Are you able to supply any more information regarding the issues you were facing?
