### ISSUE TITLE
are there Arabic language

### ISSUE THREAD

**Issue by alfuhigi** [rkhleics/wagtailmenus#287]
Hi @ababic 

thanks for this repo . 

How I can help this project for translate to Arabic language in transifex.com ?

**Comment by ababic** [comment]
Hi @alfuhigi,

Your help with Arabic translations would be much appreciated! Thank you for the offer :)

I'll review requests in Transifex today, and hopefully you will receive an invite via email.

FYI - it may be better to hold off for a week or so until the new version is released, as there may well be changes that will require retranslation.
