### ISSUE TITLE
Add a setting to ignore Promote -> Show in menus

### ISSUE THREAD

**Issue by inostia** [rkhleics/wagtailmenus#303]
At my organization, if we opt into using Wagtailmenus, we can be pretty sure that the pages that we want to include in menus are curated (i.e. we do not use dynamically generated menus from pages/child pages). We expect that we don't have to worry about including unwanted pages in our menus. As such, it's a confusing user experience for administrators to add an item to the Main Menu (or a Flat Menu) and have it not show up, only to realize that they need to navigate to the Related Page, go to the "Promote" tab, and select "Show in menu". 

This is a bit of a conflict of features: native Wagtail's menu feature and the `wagtailmenus` functionality. It'd be great to be able to switch this requirement off, because our menus are entirely admin-curated. I'd be happy to take a closer look at how this could be implemented.

**Comment by inostia** [comment]
You know @benoitvogel I think that just might solve my problem, although it is a workaround. Thank you!

**Comment by ababic** [comment]
Hi @insotia,

Thanks for the suggestion. While i can sympathise, I have to say, I don't think wagtailmenus is the best place to solve this problem. 

The root of the frustration seems to be that administrators forget to go and tick the `show_in_menus` field when they create new pages. If you take that away by making that field checked by default where appropriate (an easy change, and something you can control on a per-type basis), then things make sense as they are, no? 

You say you are not using dynamically-generated menu types, but both main and flat menus are dynamically generated too (past the top level). Ignoring `show_in_menus` entirely could well create some confusing results too, if you're rendering multi-level menus anywhere. For example, you probably don't want every news article appearing as a menu item under "News", or every event under "Events".

**Comment by inostia** [comment]
Thanks @ababic. I'm going to close this issue because I think that programatically setting the `show_in_menus` default on a per-type basis works for me. If I want to retroactively set the old pages to `True` as well I can just handle it in a migration. To be honest, I just didn't think of such a simple approach :).
