### ISSUE TITLE
Terrible migration names

### ISSUE THREAD

**Issue by robvdl** [rkhleics/wagtailmenus#304]
This is not really a bug but more a suggestion, personally I would never do this (name every migration 'auto'):

  Applying wagtailmenus.0001_initial... OK
  Applying wagtailmenus.0002_auto_20160129_0901... OK
  Applying wagtailmenus.0003_auto_20160129_2339... OK
  Applying wagtailmenus.0004_auto_20160130_0024... OK
  Applying wagtailmenus.0005_auto_20160130_2209... OK
  Applying wagtailmenus.0006_auto_20160131_1347... OK
  Applying wagtailmenus.0007_auto_20160131_2000... OK
  Applying wagtailmenus.0008_auto_20160131_2327... OK
  Applying wagtailmenus.0009_auto_20160201_0859... OK
  Applying wagtailmenus.0010_auto_20160201_1558... OK
  Applying wagtailmenus.0011_auto_20160415_1519... OK
  Applying wagtailmenus.0012_auto_20160419_0039... OK
  Applying wagtailmenus.0013_auto_20160423_1124... OK
  Applying wagtailmenus.0014_auto_20160423_1339... OK
  Applying wagtailmenus.0015_auto_20160423_1348... OK
  Applying wagtailmenus.0016_auto_20160930_0645... OK
  Applying wagtailmenus.0017_auto_20161013_1658... OK
  Applying wagtailmenus.0018_auto_20161204_2043... OK
  Applying wagtailmenus.0019_auto_20161204_2143... OK
  Applying wagtailmenus.0020_auto_20161210_0004... OK
  Applying wagtailmenus.0021_auto_20170106_2352... OK
  Applying wagtailmenus.0022_auto_20170913_2125... OK

Every migration is just called auto which is in my mind a bit lazy, I would have given the migrations proper names, might be a good idea going forward as you can't fix migration history.

**Comment by robvdl** [comment]
Feel free to close this issue, just wanted to get my point across, it's not supposed to be negative more constructive criticism.

**Comment by ababic** [comment]
Hi @robvdl, thanks for contributing.

I'm going to give you the benefit of the doubt here, and trust that you raised this, as you said, for constructive purposes. I would offer you one tip though: If you want human beings to take time out of their lives to respond to you, a little bit of kindness and politeness goes a loooooonng way. 

In relation to your point, I must admit I'm struggling to see what the benefits would be to renaming migrations after they have been created by Django. Personally, I think the migration naming approach taken by Django's `makemigrations` command is sensible enough; if it can be summed up consisely, then use a descriptive name, or if not, use a datetime string.

Would you care to explain some more about how you think this would benefit the project? Is there some kind of established pattern/approach that you try to follow?

**Comment by robvdl** [comment]
I wouldn't go and rename existing migrations anymore, that is a really bad idea. I recently came across another open source project (celery beat) which messed with migration history and they completely broke the last few migration to the point that you "can't go back" anymore. That was bad because the last release was also broken and I had already applied them in a UAT environment so I had to manually fix the database state and migration state, because we had to roll back the beat upgrade.

Anyway, generally when I create a migration, I will either rename it just before I apply it and commit it, or use the --name argument to give a meaningful name when creating it.

Mostly it gives people an idea of what was happening in migrations, some sort of train, calling them all 'auto' is not meaningful, so you have to look into each migration.

Anyway, I'll close this issue now.
