### ISSUE TITLE
Allow sub-menu for this item never checked when using condensedinlinepanel

### ISSUE THREAD

**Issue by taurgal** [rkhleics/wagtailmenus#311]
When using condensedinlinepanel if I check the tick "Allow sub-menu" then save and come back
then this tick is not checked. However one checks than the changes change hit the database. This is very annoying because if I want to make any change to any part of the menu and then save those changes then all the items in the submenu will have  "Allow sub-menu" set to False (again, checked in the database).

 For some reason setting

 WAGTAILMENUS_USE_CONDENSEDINLINEPANEL = False

did not work for me (wagtailmenus still uses condensedinlinepanel) but removing
condensedinlinepanel from the installed apps did the trick.

It is probably a condensedinlinepanel bug though...

**Comment by ababic** [comment]
Hi @taurgal. Apologies for the delayed reply. For numerous reasons, I'm finding myself with less and less spare time recently, so my open source projects are becoming a little neglected. 

Wagtailmenus does literally nothing to interfere with the default Wagtail forms or widgets, so I have to assume this is a condensedinlinepanel issue (which does).

Would you be happy to submit a pull request to make the `WAGTAILMENUS_USE_CONDENSEDINLINEPANEL = False` setting work as expected?
