### ISSUE TITLE
blockOpts is undefined when adding a Streamfield in a custom MainMenuItem

### ISSUE THREAD

**Issue by robnardo** [rkhleics/wagtailmenus#323]
Hello.  Thanks for putting this Wagtail module together!  Hoping someone can help with this bug.  I am trying to add one more field in the MainMenuItem using a CustomMainMenuItem class. 

I followed the [instructions in the docs](https://wagtailmenus.readthedocs.io/en/stable/advanced_topics/custom_menu_classes.html#overriding-the-models-used-for-main-menus) to override the default MainMenuItem

The field I am trying to add is Streamfield which contains two CharBlock types named "sub_menu_link_url " and " sub_menu_link_text".  Here is the relevant code:

``` python
class CustomMainMenuItem(AbstractMainMenuItem):
    """A custom menu item model to be used by ``wagtailmenus.MainMenu``"""
    menu = ParentalKey(
        'wagtailmenus.MainMenu',
        on_delete=models.CASCADE,
        related_name="custom_menu_items", #Add a setting to base.py to use your custom model
    )

    sub_menu = StreamField([
        ('sub_menu_field_block', SubMenuFieldBlock()),
    ], null=True, blank=True)

    # Also override the panels attribute, so that the new fields appear
    # in the admin interface

    panels = AbstractMainMenuItem.panels + [
        StreamFieldPanel('sub_menu'),
    ]

class SubMenuFieldBlock(StructBlock):
    sub_menu_link_url = CharBlock(required=True, max_length=255)
    sub_menu_link_text = CharBlock(required=True, max_length=255)
    class Meta:
        icon = 'form'
        template = "home/blocks/sub_menu_field_block.html"
```

On wagtail admin site it looks like the custom field is added successfully:

![image](https://user-images.githubusercontent.com/12520995/56371222-b6d1c680-61ca-11e9-81c9-2f856f16dd30.png)

However, when clicking the “sub menu field block”, i get a JavaScript error "TypeError: blockOpts is undefined stream.js"

![image](https://user-images.githubusercontent.com/12520995/56371762-bede3600-61cb-11e9-87cf-e25a1befac89.png)

Any ideas?

**Comment by ababic** [comment]
@robnardo Are you sure you're using `StreamFieldPanel` in your `panels` list and not just `FieldPanel`? I only ask, because this error looks similar to something I've seen before: https://github.com/wagtail/wagtail/issues/3063

**Comment by ababic** [comment]
@robnardo did you manage to figure this out yet?

**Comment by robnardo** [comment]
@ababic - i decided to destroy the docker containers and rebuild the images as well and that seemed to work.  So not an issue with the code at all - apologies.

**Comment by robnardo** [comment]
Hey @ababic - looks like this is actually still an issue.  Can you please reopen?   Explanation: so another dev on my team is not getting the error, but I am seeing the error.  We have different Wagtail versions!  The working version uses Wagtail version 2.0 and the buggy version is using Wagtail version 2.4.  I have attached the pip freeze outputs for both environments.  We both have the same version of python (which is Python v. 3.6) and we are both using docker containers (same Dockerfile).

[freeze-buggy.txt](https://github.com/rkhleics/wagtailmenus/files/3134836/freeze-buggy.txt)
[freeze-working.txt](https://github.com/rkhleics/wagtailmenus/files/3134837/freeze-working.txt)

**Comment by ababic** [comment]
@robnardo okay. This does look like it's more likely to be a regression in wagtail somewhere, rather than a problem with wagtailmenus. I'll try to find some time to investigate, but it might not be for week or so. If you're able to do any digging in the meantime, please feel free.

**Comment by ababic** [comment]
@robnardo. If you can upgrade to 2.13.1, this issue should be resolved now.

Thanks for reporting, and for digging in the things. If anything else crops up, please shout :)

**Comment by robnardo** [comment]
Hey Andy, thanks.  The new version worked!
