### ISSUE TITLE
Add support for Django 2.2 and Wagtail 2.5

### ISSUE THREAD

**Issue by pmontepagano** [rkhleics/wagtailmenus#325]
Is Wagtailmenus compatible with Django 2.2 and Wagtail 2.5?

**Comment by moreplavec** [comment]
My new project Django 2.2 + Wagtail 2.5 + WagtailMenus 2.13 and no problem so far.

**Comment by Puciek** [comment]
With django 2.2 and wagtail 2.5 it seems that it is not possible to create children-barring menus. Whenever I tick the "Allow sub-menu for this item" it does not get saved.

**Comment by ababic** [comment]
Hi @Puciek, It sounds like you might be experiencing this bug: #311

Could you try adding the following to your django settings and see if it solves your problem? 

```WAGTAILMENUS_USE_CONDENSEDINLINEPANEL = False```

**Comment by ababic** [comment]
I haven't come accross any incompatibility issues with Wagtail 2.5 or Django 2.2, so you should be good to use 2.13 with those. Support will be added officially in wagtailmenus 3.0 (I have changed the test configuration in master already)
