### ISSUE TITLE
How to bind flat menu with web category

### ISSUE THREAD

**Issue by moreplavec** [rkhleics/wagtailmenus#326]
I created simple website. Website tree is something like:

Homepage
Topic A (content page)
 * Page 1 (content page)
 * Product catalogue (product index page)
  ** Product 1 (Product page)
  ** Product 2 (Product page)
 * Page 2 (content page)
 * Page 3 (content page)
 * Page 4 (photogallery page)

Topic B
 * Page 1 (content page)
 * Page 2 (content page)
 * Page 3 (content page)
 * Product catalogue 2 (product 2nd type, index page)
  ** Product 1 (Product2 page)
  ** Product 2 (Product2 page)

Topic C
 * Page 1 (content page)
 * Page 2 (content page)
 * Page 3 (content page)

Topic D
 * Page 1 (contact page)
 * Page 2 (form page)

The problem is: for each Topic i need sidebar menu linking some pages. So i created more flat menus, specific for each topic. But in flat menus i'm missing option to specify for which tree is menu made. All topics use the same template (content_page.html) and i can't hardcode like {% flat_menu 'topic_a' %}, but i need it to bind somehow else. Please, can you help me or give me direct url i overlooked how to do it, because i think there must be some easy way how to do it, including translations.

**Comment by ababic** [comment]
Hi @moreplavec,

I would advise that having this 'loose linking' between sections and flat menus is a bad idea. What if you decide to move the sections around, or change one of the slugs for the sections? And what is keeping your menu items / pages in sync?

My recommendation is that you use the [`section_menu tag`](https://wagtailmenus.readthedocs.io/en/stable/rendering_menus/template_tag_reference.html#the-section-menu-tag) instead here, which will automatically identify the 'Topic D' page from the current one, and output a menu powered entirely by your page tree (no separate defining of menus/menu items required).

If there are additional links needed in those menus that aren't currently pages in your page tree, you have two options there:

1. Create a LinkPage model based on [`AbstractLinkPage`](https://wagtailmenus.readthedocs.io/en/stable/abstractlinkpage.html) and add the links into your tree alongside the pages
2. Or, if the additional items can be sensibly generated dynamically, and are consistent for each sectiom, you could take this approach instead: https://wagtailmenus.readthedocs.io/en/stable/menupage.html#using-menupage-to-manipulate-sub-menu-items

**Comment by ababic** [comment]
If you are really stuck on your current approach, this might work for identifying the correct menu based on the slug of the section root:

```
{% flat_menu wagtailmenus_vals.section_root.slug %}
```
