### ISSUE TITLE
Invalid template resolution

### ISSUE THREAD

**Issue by konrad147** [rkhleics/wagtailmenus#329]
Hello,

I've just installed wagtailmenus and I'm trying to use custom templates. I created templates structure as documentation suggets `/menus/main/level_1.html, level_2.html` but in this configuration `level_1` template is used to render `main_menu` and `sub_menu`. If I rename `level_1.html` to `menu.html` then `main_menu` is rendered using my `menu.html` template but `sub_menu` uses the default one (provided by wagtailmenus). If I rename `level_2.html` to `sub_menu.html` then everything works as expected.

I'm not a Django expert so there is a change that I did something wrong with templates structure but the behavior seems a bit weird.

**Comment by ababic** [comment]
@konrad147 Could you please confirm what version of wagtailmenus you are using?

**Comment by konrad147** [comment]
I use `wagtailmenus 2.13`, `django 2.1`, `wagtail 2.4` and Python `3.7`

**Comment by ababic** [comment]
Thanks @konrad147. I believe I've now resolved this issue in master, but I'll leave this issue open until the relevant releases have been made (within the next couple of weeks). I'm currently still investigating another issue, which I'd like to fix in the same set of releases if possible.

Thank you for reporting. If anything else crops up, please shout :)

**Comment by ababic** [comment]
Have recently realised this is still an issue for flat menus, so reopening until fixes are released for that also.

**Comment by ababic** [comment]
Fixed in version `3.0`
