### ISSUE TITLE
documentation for non-developers

### ISSUE THREAD

**Issue by longwuyuan** [rkhleics/wagtailmenus#33]
Hi,

I am a devops and not a developer.

Because wagtail is magnificent & beautifull, I relied on the intuitive obvious info from docs, examples & common sense to install wagtailmenus.

I don't see the menu in bare-bones step1 default install of wagtail+wagtailmenus, after following the official docs.

- I did this http://docs.wagtail.io/en/v1.6.2/getting_started/tutorial.html without the blog.
- I pip install wagtailmenus
- I added wagtailmenus to INSTALLED_APPS (visible here https://github.com/longwuyuan/devopsdragon.com )
- I added MenuPage in models.py and did the migrate process

I did not get a menu_page.html autogenerated.
I don't see menu even if i use the menu_tag in home_page.html or base.html

I apologise if asking here is not right. But then where else to ask because google throws up nothing and I am not a developer enough to inference from source bits.

Can you help me to just get a menu working.

Regards,
; Long Wu Yuan

**Comment by ababic** [comment]
Hey @longwuyuan,

The installation takes care of the migrations etc, but to get a main menu to show up, you need to define what the menu items are for your site via the Wagtail admin area. The instructions are a little bit further down in the README here:

https://github.com/rkhleics/wagtailmenus#defining-main-menu-items

Hope that helps :)

**Comment by longwuyuan** [comment]
My mistake for not providing enough data.
I did define 5 items (products,services,support...) visible in attached screenshot.

![image](https://cloud.githubusercontent.com/assets/5085914/18633347/7567e30c-7eae-11e6-8616-a6ff6f272539.png)

Thanks tons for confirming that all I need is documented install of the extension + creating items in Main Menu. I will try now one more time and update.

**Comment by ababic** [comment]
Hi @longwuyuan. I'm glad to have been able to help. I think this could be that the pages you have chosen for menu items aren't set to appear in menus. Check the 'Promote' tab in the edit page for those pages... there should be a checkbox there for you to check. It's a common gotcha... It still trips me up every now and then :)

**Comment by longwuyuan** [comment]
I got the menu and the root cause was the checkbox for "show in menus".
Hope I can give back. Lot of heartfelt gratitude.
I have goosepimples just thinking of what I can do now by just inserting the CSS CDN URLs etc.
Tons of thanks.

**Comment by ababic** [comment]
You're very kind @longwuyuan. I'm glad you managed to make some progress. Happy wagtailing! :)

**Comment by longwuyuan** [comment]
Extremely extremely happy wagtailing from now on. :-) Automatic menus is a dream come true.
Do I need to code css or will I get dropdowns for submenus.
Also, can you point me to some docs on how to paste in a sitewide CSS.
Basically, like I said, wagtail's beauty & awesomeness is being held back only because a non-developer like me needs to rely on a developer fpr menus and css. So 50% roadblock removed because of this here extension. Wishful thinking is to have another extension for CSS (or theming if you will) and I can produce 1 production website everyweek with all the other wagtail*** addons.

**Comment by ababic** [comment]
If you look around, you'll probably find that the CSS side of things is deliberately left up to developers to work out what to do, as there's so many ways you can go about it.

For example, you could use something like https://github.com/django-compressor/django-compressor or https://github.com/jazzband/django-pipeline/ to compile and combine assets at run-time, or compile assets using node, perhaps with something like gulp or grunt.

The django docs should be able to help with the basics though: https://docs.djangoproject.com/en/1.10/intro/tutorial06/

**Comment by longwuyuan** [comment]
i learnt more in one day today than I did in months/years. thanks tons. am good for now. basically better to learn django well. I was avoiding it because could not figure out where to spend time in flask vs django vs tornado. 
sorry for all noobie nonsense. much thanks again. am good for now.

**Comment by ababic** [comment]
Don't sweat it @longwuyuan. We're all noobies until we need not to be :)

**Comment by georgiana-gligor** [comment]
Thanks @ababic for the common gotcha, I fell into the same trap. I should probably think of contributing to the documentation to make this more visible.
