### ISSUE TITLE
Add sub menu to main menu

### ISSUE THREAD

**Issue by sowinski** [rkhleics/wagtailmenus#335]
Hi,

is it possible to add a sub menu to a main menu item? If yes, how?

**Comment by ababic** [comment]
Hi @sowinski. Could you elaborate a little bit more? All menu types will render sub menus for pages selected as menu items, but only if the child pages are published and have `show_in_menus` set to `True`.

**Comment by ababic** [comment]
I beleive there are some alternative menu apps out there now that are based on Streamfield, and allow multiple levels of menu items to be defined. You might like to shop around, if that's the kind of functionality you need. 

Unfortunately, Streamfield wasn't really an option when I implemented this, and there's no good way to support multiple levels in the UI using InlinePanel - it just gets incredibly messy.

**Comment by sowinski** [comment]
@ababic 
> I beleive there are some alternative menu apps 
Which one? I found only your project

I just want to add to my main menu a sub menu

For Example:
Home
Pricing
Contact
Language: English, French, Etc. (Submenu)

How can I add child elements?

**Comment by ababic** [comment]
@sowinski sorry, I'm not clear on what you're trying to achieve here. It doesn't sound like the language options should be something that is controlled in the UI... have you tried just overriding the main menu template and hardcoding the extra menu items?

**Comment by sowinski** [comment]
@ababic 
This was just an example. I just want to have a second level for a specific element.

Like you can see on the picture.
![Bildschirmfoto vom 2019-07-05 14-12-02](https://user-images.githubusercontent.com/1528746/60721691-0bb1ed00-9f2f-11e9-995a-6744a2497303.png)

**Comment by ababic** [comment]
@sowinski If the top-level item you want to add a sub-menu to is a custom link, then there's not much that wagtailmenus can do for you I'm afraid. If the top-level item is a page, then you may have some luck with this: https://wagtailmenus.readthedocs.io/en/stable/abstractlinkpage.html

**Comment by sowinski** [comment]
Hmm, really?

Maybe my English is not good enough to explain what I mean.

Even on the main page on Github there is an image with a submenu.

[https://raw.githubusercontent.com/rkhleics/wagtailmenus/master/docs/source/_static/images/repeating-item.png](url)
What is shown on the image is exactly what I want and I think this is also for most of the websites out there a default case.

Thank you :)

**Comment by ababic** [comment]
@sowinski wagtailmenus uses your existing page tree to power sub menus. So, if you select a page as a menu item and tick the "Allow sub-menu for this item" checkbox, if that pages has children that are `live` and have a `show_in_menus` value of `True`, those pages should appear as menu items in a sub menu below that item (you can control how many levels are rendered using various rendering options).

There's a bit more about this in the docs on the following page:   
https://wagtailmenus.readthedocs.io/en/stable/overview.html#multi-level-menus-generated-from-your-existing-page-tree

You might also find the template tag documentation helpful:
https://wagtailmenus.readthedocs.io/en/stable/rendering_menus/template_tag_reference.html#the-main-menu-tag

**Comment by sowinski** [comment]
@ababic 
Thank you for helping me.

I solved my problem by creating fake "page objects". I will share my code after I solved my last problem.

The last thing I need is to be able to attach to my sub_menu also "icons", "descriptions" etc. 
For the main_menu I just created an AbstractMainMenuItem with additional fields. But what can I do for my sub_menu?

**Comment by sowinski** [comment]
I solved my problem by just sub classing MenuPage (And added some custom fields  )and added it to all models. Bit complicated because I had a lot of PageModels already but it seems to work :)

**Comment by sowinski** [comment]
I was trying to use a "DummyPage" element but I got the following error.

MyCode
```
class MenuDummyPage(MenuPage):

    menu_header         = models.CharField(max_length=255, blank=True)
    menu_description    = models.CharField(max_length=255, blank=True)
    menu_icon           = models.CharField(max_length=255, blank=True)

    settings_panels = [
        FieldPanel('menu_header'),
        FieldPanel('menu_description'),
        FieldPanel('menu_icon'),
        menupage_panel
    ]
```
If I create a page and add it to the main_menu I got this error:

```
TypeError at /
issubclass() arg 1 must be a class
Request Method:	GET
Request URL:	http://10.8.0.1:8000/
Django Version:	2.0.9
Exception Type:	TypeError
Exception Value:	
issubclass() arg 1 must be a class
Exception Location:	/home/myproject/git/myvenv/lib/python3.5/site-packages/wagtailmenus/models/menus.py in _prime_menu_item, line 562
Python Executable:	/home/myproject/git/myvenv/bin/python3
Python Version:	3.5.3
Python Path:	
['/home/myproject/git/test/source/myproject',
 '/usr/lib/python35.zip',
 '/usr/lib/python3.5',
 '/usr/lib/python3.5/plat-x86_64-linux-gnu',
 '/usr/lib/python3.5/lib-dynload',
 '/home/myproject/git/myvenv/lib/python3.5/site-packages']
Server time:	Di, 9 Jul 2019 15:43:27 +0200
Error during template rendering
In template /home/myproject/git/myvenv/lib/python3.5/site-packages/wagtailmenus/templates/menus/bootstrap3/main_menu_dropdown.html, error at line 7

issubclass() arg 1 must be a class
1	{% load menu_tags %}
2	<ul class="nav navbar-nav">
3	{% for item in menu_items %}
4	    <li class="{{ item.active_class }}{% if item.has_children_in_menu %} dropdown{% endif %}">
5	        <a href="{{ item.href }}"{% if item.has_children_in_menu %} class="dropdown-toggle" id="ddtoggle_{{ item.link_page.pk }}" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"{% endif %}>{{ item.text }}{% if item.has_children_in_menu %} <span class="caret"></span>{% endif %}</a>
6	        {% if item.has_children_in_menu %}
7	        	{% sub_menu item template="menus/bootstrap3/sub_menu_dropdown.html" %}
8	        {% endif %}
9	    </li>       
10	{% endfor %}
11	</ul>
12	
```

**Comment by ababic** [comment]
Sorry @sowinski. I'm afraid I haven't seen that error before.

Sub menu items are just page objects with some additional attributes added. If you want fields from those pages to be available in sub menu templates, look at using the `use_specific` option... You don't have to subclass MenuPage for all your page types.

**Comment by sowinski** [comment]
@ababic 
Do you have a working example somewhere?

**Comment by ababic** [comment]
@sowinski You can set the default `use_specific` value on the menu itself via the CMS (Look under the **Settings** tab). You'll want to set 'Specific page usage' to  'Always', like so:

<img width="789" alt="Screenshot 2019-07-09 at 8 58 37 pm" src="https://user-images.githubusercontent.com/7779588/60919052-a93d5180-a28c-11e9-9094-e4464127a8b9.png">

Then you then can just access custom page fields in your sub menu template like so:

```
{% for item in menu_items %}
    <li class="{{ item.active_class }}">
        <a href="{{ item.href }}">
            {{ item.icon }}
            {{ item.text }}
            {{ item.description }}
         </a>
        {% if item.has_children_in_menu %}
            {% sub_menu item template=current_template %}
        {% endif %}
   </li>
{% endfor %}
```

**Comment by sowinski** [comment]
@ababic 
Awesome! Thank you! :)

Last question:
Where should I store my custom fields?

Currently I replaced **MenuPage** with **Page** from my _MenuDummyPage_ object.
```
class MenuDummyPage(Page):

    menu_header         = models.CharField(max_length=255, blank=True)
    menu_description    = models.CharField(max_length=255, blank=True)
    menu_icon           = models.CharField(max_length=255, blank=True)

    settings_panels = [
        FieldPanel('menu_header'),
        FieldPanel('menu_description'),
        FieldPanel('menu_icon'),
    ]
```

I could also add this _MenuDummyPage_ to all my other pages, so that all will have the same feature.

Is this the correct way now? :)

**Comment by ababic** [comment]
@sowinski If you have fields that you want all page types to have in your project, the best approach is to define an abstract `BasePage` model, and subclass that for all your other page types. For example:

```
class BasePage(Page):
    menu_header = models.CharField(max_length=255, blank=True)
    menu_description = models.CharField(max_length=255, blank=True)
    menu_icon =  models.CharField(max_length=255, blank=True)
    
    # including the original panels here too, but that's up to you
    settings_panels = Page.settings_panels + [
        FieldPanel('menu_header'),
        FieldPanel('menu_description'),
        FieldPanel('menu_icon'),
    ]

    class Meta:
        abstract = True  # this is important


class GeneralPage(BasePage):
    pass

class SomeOtherPage(BasePage):
    pass
```

**Comment by sowinski** [comment]
@ababic 
Thank you :) That's working perfect now!

**Comment by alfredo-ardito** [comment]
Hello, is there a fully working example with sub menus?

**Comment by ababic** [comment]
@alfredo-ardito There are some new examples in the docs to help explain how multi-level menus work:
https://wagtailmenus.readthedocs.io/en/latest/overview.html#multi-level-menu-examples

If you want to see actual working code, you can clone the project and[ follow these steps](https://wagtailmenus.readthedocs.io/en/latest/contributing/index.html#developing-locally) to run the test project on your local machine, or you can just explore the [test app code online](https://github.com/rkhleics/wagtailmenus/tree/master/wagtailmenus/tests), if that's more your thing.

**Comment by Durgavasu58** [comment]
does Bootstrap5 is supported for wagtail-nav-menus?????

**Comment by sowinski** [comment]
@Durgavasu58 
Unfortunately this project is dead. No one is currently maintaining this package any more. 
You should consider to avoid this package, because currently it is not supporting the newer wagtail versions..
(Hopefully this changes soon)

>> does Bootstrap5 is supported for wagtailmenus?????
You can use this package with any css framework you want. What stops you using bootstrap 5?

**Comment by Durgavasu58** [comment]
i need a mutlievel dropdown for my project
