### ISSUE TITLE
Remove condensedinlinepanel integration/recommendation

### ISSUE THREAD

**Issue by ababic** [rkhleics/wagtailmenus#336]
At the time, adding support for `condensedinlinepanel` made sense, because it made the UI much cleaner. However, most of the issues raised these days are related to that apps limited support for certain field types, and the app doesn't seem to be maintained any longer, so I don't see these issues being fixed any time soon.

**Comment by ramonakira** [comment]
Also, when using condensedinlinepanel the checkbox for `Allow sub-menu for this item:` does not appear to work, although under water, it does.
