### ISSUE TITLE
How do you display menu heading in the template?

### ISSUE THREAD

**Issue by vinodMS** [rkhleics/wagtailmenus#344]
I am referring to [show_menu_heading](https://github.com/rkhleics/wagtailmenus/blob/master/docs/source/rendering_menus/template_tag_reference.rst#id140) here, how exactly do I refer to the heading in template? I've look around but cannot find anything.

Here's my code block

footer.html
`{% flat_menu 'about-us-footer' max_levels=1 use_specific=1 template="menu/footer_flat_menu.html" show_menu_heading=True%}
`

menu/footer_flat_menu.html
```
{% load menu_tags %}

<nav class="level navigation nav-box">
    {% for item in menu_items %}
        <p class="level-item has-text-centered">
            <a href="{{ item.href }}" class="has-text-black">
                {{ item.text }}
            </a>
        </p>
    {% endfor %}
</nav>
```

**Comment by ababic** [comment]
Hi @vinodMS,

Ah, yes. It looks like a few variables are missing from the documentation here:
https://wagtailmenus.readthedocs.io/en/stable/rendering_menus/custom_templates.html#what-context-variables-are-available-to-use

All menu types add the current menu instance to the template context as `menu_instance`, so I would try using `{{ menu_instance.heading }}`

**Comment by vinodMS** [comment]
Thank you, that worked.

**Comment by vinodMS** [comment]
Just for future reference, to get the heading it is {{ menu_instance.title }}

**Comment by ababic** [comment]
@vinodMS Note that `title` and `heading` are separate fields on flat menus: `{{ menu_instance.title }}` gives you `title`, while `{{ menu_instance.heading }}` gives you `heading`
