### ISSUE TITLE
active_class not returning data on main_menu

### ISSUE THREAD

**Issue by vinodMS** [rkhleics/wagtailmenus#345]
I've read through the document, but somehow I'm not able to get 'active_class' to return any data even if the url matches the menu item link.

Here is my code implementation,

```
#.../header.html
{% main_menu template="menu/main_menu.html"%}
```

```
#.../main_menu.html
<div class="navbar-menu">
        {% for item in menu_items %}
            <a href="{{ item.href }}" class="navbar-item {{ item.active_class }}"
               style="padding-top: 1rem;padding-bottom: 1rem;font-family: '{{ settings.base.SiteSettings.top_menu_font_style }}', serif;color: {{ settings.base.SiteSettings.top_menu_font_colour }}">
                {{ item.text }}
            </a>
        {% endfor %}
    </div>
```

I've tried applying` apply_active_classes=true`, that didn't apply either. What am I missing?

**Comment by ababic** [comment]
Hi @vinodMS. Did you add the `context_processor` to `TEMPLATES` setting, as shown in step 3 here: https://wagtailmenus.readthedocs.io/en/stable/installation.html

**Comment by vinodMS** [comment]
Hi @ababic, I did have the `context_processor` in the template settings. For some reason I had `apply_active_classes=true` in `main_menu`. Although `apply_active_classes` is set to true by default, explicitly setting it to true hides the active class being output.

**Comment by ababic** [comment]
Hi @vinodMS. `true` is an undefined variable, and will be interpreted by the template tag as `None` (which if actually 'falsey' instead of 'truthful'). In Django template tags, you should use `True` (with an upper-case T) to mean true, like you do in Python itself.

**Comment by vinodMS** [comment]
My bad, you are right. I guess I got confused by this line found here - [https://wagtailmenus.readthedocs.io/en/stable/rendering_menus/template_tag_reference.html?highlight=apply_active_classes#id8](https://wagtailmenus.readthedocs.io/en/stable/rendering_menus/template_tag_reference.html?highlight=apply_active_classes#id8)

> you can override this by adding apply_active_classes=true to the tag in your template.
