### ISSUE TITLE
Managing Main and Flat menus

### ISSUE THREAD

**Issue by moreplavec** [rkhleics/wagtailmenus#346]
I used wagtailmenus for my latest project. I need flat menus and main menu. Currently i have Main menu (main menu, autogenerated with 1st level dropdown), Top menu (flat menu), Bottom menu (flat menu) and Sidebar menu (flat menu, autogenerated based on root page slug). All linked by slug in template. All works fine, until i want to make main and flat menus independent. My problem is like:

```
Page 1 (Show in menus = True)
   Subpage A (Show in menus = True)
   Subpage B (Show in menus = False)
Page 2
...
...
```

Top menu is auto-generated for root and 1st level items (Page 1 with dropdown Subpage A and Subpage B)...

BUT: **how to show Subpage B to flat menu, but not to show in auto-generated Main menu**? I was thinking to let Subpage B with Show in menus = False (to hide it from main menu) and somehow force flat menu to show it, but how? Or is there any better way how to make independent main and flat menu while using page same tree?

Thanks for tip or link to doc, i haven't found such function.

**Comment by ababic** [comment]
Hi @moreplavec,

It sounds like hooks might be a good candidate for this.

If the pages can be filtered out easily enough at the queryset level, adding additional filters via [`menus-modify-base-page-queryset`](https://wagtailmenus.readthedocs.io/en/stable/advanced_topics/hooks.html#menus-modify-base-page-queryset) would be best, as not fetching the pages from the database to begin with would be more efficient.

However, if you would be dependant on custom page fields to apply additional filtering, it might be easier to use [`menus_modify_raw_menu_items`](https://wagtailmenus.readthedocs.io/en/stable/advanced_topics/hooks.html#menus-modify-raw-menu-items), and exclude items there instead.

**Comment by moreplavec** [comment]
Thanks for replay. The problem is, that hook can filter or work with menu items AFTER page selection.

```
By default, get_base_page_queryset() applies a few simple filters to prevent certain pages appearing in your menus:

Page.objects.filter(live=True, expired=False, show_in_menus=True)
```

I'd like to modify this query for flat_menu to include show_in_menus=(True or False). Main menu will stay and visibility is done by show_in_menu, for flat_menu is enough to publish and to add the page to specific flat_menu.

So, can I modify the base page queryset for flat_menu or is there other way? I still need to control main and flat menu separated.

**Comment by ababic** [comment]
@moreplavec both hooks receive a number of keyword arguments that will allow you to conditionally override the behaviour for just one menu type.

**Comment by ababic** [comment]
`menus_modify_raw_menu_items` might be a better choice in your case, as `current_level` will be available for you to use in conditions also. Check out the example in the docs :)

**Comment by ababic** [comment]
Closing this issue, as I don't feel there's really any more to add.
