### ISSUE TITLE
Using regroup with main_menu

### ISSUE THREAD

**Issue by davemerwin** [rkhleics/wagtailmenus#347]
I'm struggling to regroup the main_menu with regrouping into two separate menus. Those with children and those without. Is there a way to do this that I'm not seeing?

**Comment by ababic** [comment]
@davemerwin I'd love to help, but I'm not currently understanding what it is you're trying to achieve here. Could you provide a bit more info?

**Comment by davemerwin** [comment]
In case anyone is interested here's how you can do this:

    {% load menu_tags wagtailcore_tags %}
    {% regroup menu_items by has_children_in_menu as items %}
