### ISSUE TITLE
Deprecation error for EditHandler.bind_to_model(model)

### ISSUE THREAD

**Issue by jorenham** [rkhleics/wagtailmenus#348]
It will be deprecated in Wagtail 2.7.
https://github.com/rkhleics/wagtailmenus/blob/dc7cd65ae2769d2cf4a5d523f60965088f9a0201/wagtailmenus/views.py#L57

**Comment by ababic** [comment]
Thanks for the spot @jorenham. There are a few things that break when testing against 2.7 currently, so I'll address this along with those.

**Comment by Kernub** [comment]
Is there any list of things that break after upgrading to 2.7?

**Comment by ababic** [comment]
New v3.0 release supports Wagtail 2.7, so closing this
