### ISSUE TITLE
How to work with submenus? Still missing order

### ISSUE THREAD

**Issue by moreplavec** [rkhleics/wagtailmenus#353]
Hello again, 

maybe there is something new or I'm missing something in doc, but how do you sort submenu pages in main menu? Now i can generate all subpages for page in main menu, but how to set order for this pages?

**Comment by ababic** [comment]
Wagtailmenus respects the 'natural ordering' of pages, which is determined by the `path` value. You can see / modify this order from the explorer by clicking the little 'reorder' icon at the top of the first column:

http://docs.wagtail.io/en/stable/editor_manual/finding_your_way_around/the_explorer_page.html#reordering-pages

**Comment by ababic** [comment]
Am closing this issue

**Comment by moreplavec** [comment]
Thanks, my fault.
