### ISSUE TITLE
'TabbedInterface' object has no attribute 'bind_to_model'

### ISSUE THREAD

**Issue by lacymorrow** [rkhleics/wagtailmenus#359]
wagtailmenus/mainmenu/edit/2/
--
wagtail version 2.7.1
wagtailmenus version 2.13.1
DJANGO VERSION 2.2.9
AttributeError: 'TabbedInterface' object has no attribute 'bind_to_model'
/usr/local/lib/python3.6/site-packages/wagtailmenus/views.py in get_edit_handler, line 57

Has anyone come across this? I'm trying wagtailmenus for the first time.

**Comment by ababic** [comment]
Hi @lacymorrow. Are you sure on the wagtailmenus version there? This has been fixed for a while:
https://github.com/rkhleics/wagtailmenus/blob/15f3e8aaf8b9d4bf12224ff2dee431035103f159/wagtailmenus/views.py#L57-L60

**Comment by lacymorrow** [comment]
I must have an old version in my environment somewhere, that check is not in my file.

Thanks for clarifying @ababic!
