### ISSUE TITLE
Iterating over sub_menu item doubt

### ISSUE THREAD

**Issue by sabueso** [rkhleics/wagtailmenus#363]
Hi!

I was trying to iterate over a submenu items, but I did not find any simple way to do this in docs:

First, I've defined a new template for the sub_menu:
```
{% for item in menu_items %}
     {% if item.text|lower == request.path|cut:"/" %}
        {% if item.has_children_in_menu %}
          {% sub_menu item template="home/menu_selector_page_submenu.html" %}
       {% endif %}
   {% endif %}	
{% endfor %}
```

And then, in "menu_selector_page_submenu.html" I've used something like this to render ONLY the names of each submenu (I want to use those names in a sort of automatic-options-html-populator for a service page):

```
{% for object in sub_menu.items %}
	{{ object.text }}
{% endfor %}
```

Is this a correct way to iterate over sub_menu object? Any thoughts? I've obtained what I want, but I'm not pretty sure if this is going to work right.

Thanks!

**Comment by ababic** [comment]
Hi @sabueso. I think you may find the [`add_sub_menus_inline`](https://wagtailmenus.readthedocs.io/en/stable/rendering_menus/template_tag_reference.html#add-sub-menus-inline) option useful in this case. This way, you don't need to call the `{% sub_menu %}` tag at all, and don't need to have a separate template. You could just do:

```
{% for item in menu_items %}
     {% if item.text|lower == request.path|cut:"/" %}
        {% if item.sub_menu %}
            {% for sub_item in item.sub_menu.items %}
                {{ sub_item.text }}
            {% endfor %}
       {% endif %}
   {% endif %}	
{% endfor %}
```

If you'd like for sub menus to be added to menu items in this way all of the time, you can use the  [`WAGTAILMENUS_DEFAULT_ADD_SUB_MENUS_INLINE`](https://wagtailmenus.readthedocs.io/en/stable/settings_reference.html#wagtailmenus-default-add-sub-menus-inline) setting to make it the default behaviour.

**Comment by sabueso** [comment]
Thanks! I will give it a try!
