### ISSUE TITLE
NULL-value in column »site_id« violates Not-Null-Constraint if there's no Site defined

### ISSUE THREAD

**Issue by Mrfuyu** [rkhleics/wagtailmenus#367]
I have a django project in production and added now wagtail and wagtailmenus to it. The project should work also without wagtail setup. But it produces a server error if wagtail has no site assosiated because wagtailmenus does not check if there's site. If there's not site wagtailmenus should return simple no menu.

In the templatetags/menu_tags.py there is e.g. main_menu and before doing something else a check if the wagtail Site object exists should be done and if not just return "".

Just for a quick fix by adding `if Site.objects.all().count() == 0:` did the job.

```
from wagtail.core.models import Page, Site

@register.simple_tag(takes_context=True)
def main_menu(
    context, max_levels=None, apply_active_classes=True,
    allow_repeating_parents=True, show_multiple_levels=True,
    template='', sub_menu_template='', sub_menu_templates=None,
    use_absolute_page_urls=False, add_sub_menus_inline=None,
    **kwargs
):
    if Site.objects.all().count() == 0:
        return ""
    validate_supplied_values('main_menu', max_levels=max_levels)

    if not show_multiple_levels:
        max_levels = 1

    menu_class = settings.models.MAIN_MENU_MODEL
    return menu_class.render_from_tag(
        context=context,
        max_levels=max_levels,
        apply_active_classes=apply_active_classes,
        allow_repeating_parents=allow_repeating_parents,
        use_absolute_page_urls=use_absolute_page_urls,
        add_sub_menus_inline=add_sub_menus_inline,
        template_name=template,
        sub_menu_template_name=sub_menu_template,
        sub_menu_template_names=split_if_string(sub_menu_templates),
        **kwargs
    )
```

**Comment by ababic** [comment]
Hi @Mrfuyu. If you have a wagtail project with no site defined, this failure will probably be the least of your problems. Sites play a key role in page url generation, which is why Wagtail creates a default one for you in its migrations. 

This error gives you a clue to what the problem is and how to fix it. I think I'd rather that be the case, instead of returning an empty string.
