### ISSUE TITLE
Generate menu without manual creating it

### ISSUE THREAD

**Issue by moreplavec** [rkhleics/wagtailmenus#376]
I'd like to use wagtail menus for my new e-shop. I have full automatized import of product, including putting in categories, categories are auto-generated too. So i need to autogenerate category menu for sidebar. Is Wagtailmenus the right choice or it's better just filter CategoryPages with show_in_menus = 1 and generate manually? Or maybe is there function to autopopulate main menu each time i import something?

Thanks for answer or link, i tried to search the doc, but havn't found anything for my case.

**Comment by ababic** [comment]
@moreplavec my advice - keep things simple. If all you want to do is display a list of links to pages of a specific type, do exactly that: Get a queryset into the context (a custom context manager might be useful), and have a template render them.
