### ISSUE TITLE
Link to a document instead of a page or custom url

### ISSUE THREAD

**Issue by danlerche** [rkhleics/wagtailmenus#384]
Would be really great if menu items could link to internal wagtail documents (from wagtail.documents.models import Document) much in the same way it links to internal pages.  I'm guessing this is a feature request but curious if there's anyway to do this now?

**Comment by ababic** [comment]
Hi @danlerche,

This has been requested a couple of times before, and I have always declined it on the basis that it sounds like a poor user experience. If content is important enough to be linked to from a menu, then I feel it should be important enough to have a real page, where the content is made accessible to everybody - egardless of what other software they have installed.

If this is something you really must implement, wagtailmenus supports 
[custom menu and menu item models](https://wagtailmenus.readthedocs.io/en/stable/advanced_topics/custom_menu_classes.html#using-custom-menu-classes-and-models).
