### ISSUE TITLE
Generate menu from page tree

### ISSUE THREAD

**Issue by moreplavec** [rkhleics/wagtailmenus#387]
I tried to search the doc and found how to create/manage and populate menu for the first time. But is there a way how to not create main menu manually, but generate whole main menu directly from page tree? I mean, client is using simple wagtail site as note-taking app and it's boring with each new page check page's menu checkbox and go to main menu to add the new page to tree which is direct copy of tree how pages are created. It would be great just generate menu directly from tree. Is it possible now?

**Comment by ababic** [comment]
@moreplavec You might like to try the `autopopulate_main_menus` command. It's currently mentioned in the docs on the installation instructions page: https://wagtailmenus.readthedocs.io/en/stable/installation.html

**Comment by ababic** [comment]
Hi @moreplavec. You should be to put something together quite easily if that's something you want to do in your project. You may find it helpful to check out what's going on in `autopopulate_main_menus`:  
https://github.com/rkhleics/wagtailmenus/blob/master/wagtailmenus/management/commands/autopopulate_main_menus.py
