### ISSUE TITLE
AttributeError: 'VideoMenu' object has no attribute '_registered_menu_items'

### ISSUE THREAD

**Issue by leonardorhojas** [rkhleics/wagtailmenus#400]
HI

I have installed recently wagtailmenus to my wagtal project, currently I have another extra torchbox libraries, included wagtailvideos.

I just installed the wagtailvideo library and then after the basic setup I got the following error:

env_1            | AttributeError: 'VideoMenu' object has no attribute '_registered_menu_items'
env_1            | Internal Server Error: /admin/
env_1            | Traceback (most recent call last):
env_1            |   File "/usr/local/lib/python3.7/dist-packages/django/core/handlers/exception.py", line 34, in inner
env_1            |     response = get_response(request)
env_1            |   File "/usr/local/lib/python3.7/dist-packages/django/core/handlers/base.py", line 115, in _get_response
env_1            |     response = self.process_exception_by_middleware(e, request)
env_1            |   File "/usr/local/lib/python3.7/dist-packages/django/core/handlers/base.py", line 113, in _get_response
env_1            |     response = wrapped_callback(request, *callback_args, **callback_kwargs)
env_1            |   File "/usr/local/lib/python3.7/dist-packages/django/views/decorators/cache.py", line 44, in _wrapped_view_func
env_1            |     response = view_func(request, *args, **kwargs)
env_1            |   File "/usr/local/lib/python3.7/dist-packages/wagtail/admin/urls/__init__.py", line 102, in wrapper
env_1            |     return view_func(request, *args, **kwargs)
env_1            |   File "/usr/local/lib/python3.7/dist-packages/wagtail/admin/decorators.py", line 34, in decorated_view
env_1            |     return view_func(request, *args, **kwargs)
env_1            |   File "/usr/local/lib/python3.7/dist-packages/wagtail/admin/views/home.py", line 119, in home
env_1            |     'user': request.user
env_1            |   File "/usr/local/lib/python3.7/dist-packages/django/shortcuts.py", line 36, in render
env_1            |     content = loader.render_to_string(template_name, context, request, using=using)
env_1            |   File "/usr/local/lib/python3.7/dist-packages/django/template/loader.py", line 62, in render_to_string
env_1            |     return template.render(context, request)
env_1            |   File "/usr/local/lib/python3.7/dist-packages/django/template/backends/django.py", line 61, in render
env_1            |     return self.template.render(context)
env_1            |   File "/usr/local/lib/python3.7/dist-packages/django/template/base.py", line 171, in render
env_1            |     return self._render(context)
env_1            |   File "/usr/local/lib/python3.7/dist-packages/django/test/utils.py", line 96, in instrumented_test_render
env_1            |     return self.nodelist.render(context)
env_1            |   File "/usr/local/lib/python3.7/dist-packages/django/template/base.py", line 937, in render
env_1            |     bit = node.render_annotated(context)
env_1            |   File "/usr/local/lib/python3.7/dist-packages/django/template/base.py", line 904, in render_annotated
env_1            |     return self.render(context)
env_1            |   File "/usr/local/lib/python3.7/dist-packages/django/template/loader_tags.py", line 150, in render
env_1            |     return compiled_parent._render(context)
env_1            |   File "/usr/local/lib/python3.7/dist-packages/django/test/utils.py", line 96, in instrumented_test_render
env_1            |     return self.nodelist.render(context)
env_1            |   File "/usr/local/lib/python3.7/dist-packages/django/template/base.py", line 937, in render
env_1            |     bit = node.render_annotated(context)
env_1            |   File "/usr/local/lib/python3.7/dist-packages/django/template/base.py", line 904, in render_annotated
env_1            |     return self.render(context)
env_1            |   File "/usr/local/lib/python3.7/dist-packages/django/template/loader_tags.py", line 150, in render
env_1            |     return compiled_parent._render(context)
env_1            |   File "/usr/local/lib/python3.7/dist-packages/django/test/utils.py", line 96, in instrumented_test_render
env_1            |     return self.nodelist.render(context)
env_1            |   File "/usr/local/lib/python3.7/dist-packages/django/template/base.py", line 937, in render
env_1            |     bit = node.render_annotated(context)
env_1            |   File "/usr/local/lib/python3.7/dist-packages/django/template/base.py", line 904, in render_annotated
env_1            |     return self.render(context)
env_1            |   File "/usr/local/lib/python3.7/dist-packages/django/template/loader_tags.py", line 150, in render
env_1            |     return compiled_parent._render(context)
env_1            |   File "/usr/local/lib/python3.7/dist-packages/django/test/utils.py", line 96, in instrumented_test_render
env_1            |     return self.nodelist.render(context)
env_1            |   File "/usr/local/lib/python3.7/dist-packages/django/template/base.py", line 937, in render
env_1            |     bit = node.render_annotated(context)
env_1            |   File "/usr/local/lib/python3.7/dist-packages/django/template/base.py", line 904, in render_annotated
env_1            |     return self.render(context)
env_1            |   File "/usr/local/lib/python3.7/dist-packages/django/template/loader_tags.py", line 62, in render
env_1            |     result = block.nodelist.render(context)
env_1            |   File "/usr/local/lib/python3.7/dist-packages/django/template/base.py", line 937, in render
env_1            |     bit = node.render_annotated(context)
env_1            |   File "/usr/local/lib/python3.7/dist-packages/django/template/base.py", line 904, in render_annotated
env_1            |     return self.render(context)
env_1            |   File "/usr/local/lib/python3.7/dist-packages/django/template/library.py", line 192, in render
env_1            |     output = self.func(*resolved_args, **resolved_kwargs)
env_1            |   File "/usr/local/lib/python3.7/dist-packages/wagtail/admin/templatetags/wagtailadmin_tags.py", line 82, in main_nav_js
env_1            |     return admin_menu.media['js']
env_1            |   File "/usr/local/lib/python3.7/dist-packages/wagtail/admin/menu.py", line 78, in media
env_1            |     media += item.media
env_1            |   File "/usr/local/lib/python3.7/dist-packages/wagtail/admin/menu.py", line 106, in media
env_1            |     return Media(js=[static('wagtailadmin/js/submenu.js')]) + self.menu.media
env_1            |   File "/usr/local/lib/python3.7/dist-packages/wagtail/admin/menu.py", line 77, in media
env_1            |     for item in self.registered_menu_items:
env_1            |   File "/usr/local/lib/python3.7/dist-packages/wagtail/admin/menu.py", line 64, in registered_menu_items
env_1            |     if self._registered_menu_items is None:
env_1            | AttributeError: 'VideoMenu' object has no attribute '_registered_menu_items'

the error appears just after installing the library and open your project admin: localhots:8000/admin in my case.

this are the torchbox libraries I'm ussing:

# torchbox libraries
wagtailvideos==2.10.2
wagtail-footnotes==0.6.0
wagtailmenus==3.0.2

this is the major parts of my setting file:
```

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            os.path.join(BASE_DIR, 'v2/templates/v2'),
            os.path.join(BASE_DIR, 'api/templates/api'),
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'social_django.context_processors.backends',
                'social_django.context_processors.login_redirect',
                'wagtail.contrib.settings.context_processors.settings',
                'wagtailmenus.context_processors.wagtailmenus',
            ],
            'debug': False,
        },
    },
]


INSTALLED_APPS = [
    # Django apps
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sitemaps',

    # Third party apps required by project and Wagtail
    'modelcluster',
    # Compressor is no longer required by wagtail
    # but we still like offline compression of assets
    'compressor',
    'taggit',
    'social_django',
    # 'django_nose',

    # Security
    'csp',

    # CORS
    'corsheaders',

    # Project apps that override wagtail functionality
 ....

    # Wagtail apps
    'wagtail.contrib.forms',
    'wagtail.contrib.redirects',
    'wagtail.embeds',
    'wagtail.sites',
    'wagtail.users',
    'wagtail.snippets',
    'wagtail.documents',
    'wagtail.images',
    'wagtail.search',
    'wagtail.admin',
    'wagtail.core',
    'wagtail.contrib.sitemaps',
    'wagtail.api',
    'wagtail.contrib.settings',
    'rest_framework',
    # required for wagtailmenus
    'wagtail.contrib.modeladmin',
    # torchbox apps
    'wagtailmenus',
    'wagtailvideos',
    'wagtail_footnotes',

   ...
    'wagtail_webstories',
]

```

**Comment by ababic** [comment]
Hi @leonardorhojas. What happens if you uninstall wagtailmenus and restart the app? Does the issue go away?

If not, you can probably rule this app out as the cause of the problem.

**Comment by leonardorhojas** [comment]
Hi yes, when I unistall wagtailmenus the issues doesn't appear again

**Comment by ababic** [comment]
@leonardorhojas I see you also raised this issue on `wagtailvideos`, which is where the problem actually is. See my latest reply on https://github.com/neon-jungle/wagtailvideos/issues/82
