### ISSUE TITLE
Support for wagtail >= 2.15 

### ISSUE THREAD

**Issue by Alihassanc5** [rkhleics/wagtailmenus#456]
I am facing a similar issue as described in https://github.com/jazzband/wagtailmenus/issues/435. Currently, I am using Django 3.2, wagtailmenus 3.1.3 and Wagtail 2.15. However, upgrading wagtailmenus from version 3.1.3 to 3.1.8 necessitates a major update from Wagtail 2.15 to 4.1. In my opinion, it would be beneficial if wagtailmenus also supported previous Wagtail versions.

**Comment by MrCordeiro** [comment]
Sorry, @Alihassanc5, but as an OSS, we don't have the resources to support previous Wagtail versions indefinitely, so we follow Wagtail's release schedule: https://github.com/wagtail/wagtail/wiki/Release-schedule.

wagtaimenus v3.1.2 should support Wagtail 2.15 and 3.x
wagtaimenus v3.1.3 should support Wagtail 3.x and 4.0

So you should be covered in the older versions of Wagtailmenus, right?

Remember that it is highly recommended always to have your projects in the latest LTS versions so the impact of a major version change is smaller.
