### ISSUE TITLE
A signal for when a menu is saved

### ISSUE THREAD

**Issue by Temeez** [rkhleics/wagtailmenus#51]
Hi, awesome app, but would it be possible to get a signal or two for when a main/flat menu is saved? I'd need it for clearing main menu template cache, which currently only triggers via page (un)publishing.

I need to cache the main menu because it adds +200ms TTFB time to each page load, which is not accetable, fortunately template caching exists. :)

**Comment by ababic** [comment]
Hi @Temeez. I could well be wrong, but I think both the `MainMenu` and `FlatMenu` models emit all of the default django model signals, which you should be able to hook into for this. Have you tried using any of the following? 

https://docs.djangoproject.com/en/1.10/ref/signals/#module-django.db.models.signals

**Comment by Temeez** [comment]
You are correct, post_save at least works. I'm not sure why I totally forgot about default django signals, thanks.
I'd suggest you put a "Signals" section in the readme which says that djangos default model signals work with the menus. :)

**Comment by ababic** [comment]
Thanks for the recommendation. I'm glad you managed to find a solution :)
