### ISSUE TITLE
Missing Migration in v1.5

### ISSUE THREAD

**Issue by nadersoliman** [rkhleics/wagtailmenus#52]
Hello,

When running `makemgirations` it looks like there is a missing migration that tries to alter fields url_append

```
    operations = [
        migrations.AlterField(
            model_name='flatmenuitem',
            name='url_append',
            field=models.CharField(blank=True, help_text="Use this to optionally append a #hash or querystring to the above page's URL.", max_length=255, verbose_name='append to URL'),
        ),
        migrations.AlterField(
            model_name='mainmenuitem',
            name='url_append',
            field=models.CharField(blank=True, help_text="Use this to optionally append a #hash or querystring to the above page's URL.", max_length=255, verbose_name='append to URL'),
        ),
    ]
```

Something that could be related is that the `help_text` for these fields is not calling the translation function as in 
https://github.com/rkhleics/wagtailmenus/blob/master/wagtailmenus/models.py#L122

```
    url_append = models.CharField(
        verbose_name=_("append to URL"),
        max_length=255,
        blank=True,
        help_text=(
            "Use this to optionally append a #hash or querystring to the "
            "above page's URL.")
    )
```

So what do you think?

**Comment by ababic** [comment]
Hi @nadersoliman. Thank you for raising this. I think you're on to something there! The `help_text` for that field should be wrapped for translation like the others. I don't suppose you could check whether that solves the problem?

**Comment by nadersoliman** [comment]
@ababic I tried to change the `help_text` to use the translation function, still it generated a migration, strange though that wagtailmenus v1.5 generated a migration 0016_ but didn't detect this change for you. 

So despite the possible fix in the model a migration is still being generated (the previous migration for this field is at `0012_auto_20160419_0039.py` and the help text is treated as binary string).

I am suspecting django version change, mine is `1.10.2`, with wagtail `1.6.3` so what about your versions?

**Comment by ababic** [comment]
Thanks for investigating @nadersoliman. I have tried running `makemigrations` again (before and after wrapping the text for translation), and am still seeing no `No changes detetcted` when using those exact same versions of django and wagtail. 

I'm guessing it must have something to do with the string being a binary string in `0012_auto_20160419_0039.py`. Could you try changing that to a regular string in the migration and see if that solves the problem? That, and differing versions of Python may be to culprit.

**Comment by nadersoliman** [comment]
@ababic You nailed it down, in migration `0012_auto_20160419_0039.py` there are two instances of binary strings, I changed one to normal string and left the other. `makemgirations` created a migration for only one field (the one remaining as binary). 

Then changed the two instances to non-binary strings did not trigger any migrations as you expected.  (of course deleted the created migration file from the previous step first ;) )

my python version is `3.5.1`

well, thanks a lot for lending a hand in this and great work with this module, thanks guys.

**Comment by ababic** [comment]
@nadersoliman Thanks! I'm glad that solved the issue. I'm really not sure how binary strings ended up in the migration... it's not something I've really ever seen before. I will doctor that migration and put a new bug fix release out soon. 

Thanks again for you help. I'm glad to here you're finding wagtailmenus useful :)
