### ISSUE TITLE
Docs are not up to date in the github page

### ISSUE THREAD

**Issue by frague59** [rkhleics/wagtailmenus#69]
Hi, 
The docs are not up to date in the github repo: they talk about a context processor, which is not available anymore.

You should also consider using ReST as docs files which willl be more readable on pypi, and more "pythonic", GitHub supports them as soon as they are suffixed with `rst`.

I'll try to change those files and propose a pull from my own repository.
Thanks !

**Comment by adriaant** [comment]
The context_processor is new in the master branch, afaik, and should be released hopefully soon (since current release version is not completely compatible with wagtail 1.7).

**Comment by ababic** [comment]
Hi @frague59. As @adriaant says, you're looking at the master branch, so some things aren't in the PyPi release version yet. There's a 1.7 release planned for this Friday, which will include the context_processor and the docs will be relevant to that version.

I know about ReST, but unfortunately, I'm just not that familiar with it, so find it hard to manage (I don't have anybody helping me out with that side of things, so I'd rather use something I'm comfortable with). Eventually we'll have some proper docs (put together in ReST) and the README will be far less important, but it's a little down the list of priorities right now.

**Comment by SalahAdDin** [comment]
:+1: for update documentation.
