### ISSUE TITLE
Siblings only menu ?

### ISSUE THREAD

**Issue by muhammad-saleh** [rkhleics/wagtailmenus#7]
Hi,
Thanks a lot for your great plugin it really helps a lot

I want to have a siblings only menu (Menu which has only pages at the same level, So no children and no parents)

I tried to change the section menu to do so but with no luck

So is there's something that I'm missing ?
Do you recommend a specific way of doing so ?

Thanks.

**Comment by ababic** [comment]
Hi @muhammad-saleh.

You could try using the `{% children_menu %}` tag. You can pass a 'parent_page' argument to that, so you could do something like `{% children_menu parent_page=self.get_parent %}` in your template to output siblings (including the current page).

**Comment by muhammad-saleh** [comment]
Hi @ababic
Thanks a lot it works 👍 
I also added the active class on the active element using request.path

**Comment by ababic** [comment]
Hi @muhammad-saleh, 

Glad you got it working. You may find it easier to add `apply_active_classes=True` to the tag in your template to get active class highlighting, rather than doing something custom.

**Comment by muhammad-saleh** [comment]
Used it now, much better
Thanks again
