### ISSUE TITLE
unorderable types: NoneType() > int()

### ISSUE THREAD

**Issue by adriaant** [rkhleics/wagtailmenus#76]
unorderable types: NoneType() > int() error shown when rendering template. Bug after upgrading from 1.6.1 to 2.0.0. Error happens just by invoking {% main_menu %}

**Comment by ababic** [comment]
Thanks for raising @adriaant. Will investigate today and hopefully get a fix in place.

**Comment by adriaant** [comment]
If I pass in max_levels=2 explicitly to `mainmenu` template tag, then it works.

**Comment by ababic** [comment]
Hi @adriaant. Did you run migrations first?

**Comment by adriaant** [comment]
Yes, I did.

**Comment by ababic** [comment]
Hi @adriaant. I've just updated a project locally to version `2.0` and didn't have this issue. Are you able to provide the full trace perhaps? If you don't want to post here, you can email me at ababic@rkh.co.uk

**Comment by ababic** [comment]
@adriaant If think I know what might be causing this. Any chance you could try the out the master branch and see if you still have the problem?

**Comment by ababic** [comment]
@adriaant Any joy?

**Comment by ababic** [comment]
@adriaant I've pushed a bug-fix release `2.0.1` which should resolve this issue. Any chance you can try it out and let me know if you're still having issues?

**Comment by adriaant** [comment]
2.0.1 fixes the issue. Thanks for such a quick fix!
