### ISSUE TITLE
Use seo_title in prior to title for Pages

### ISSUE THREAD

**Issue by robmoorman** [rkhleics/wagtailmenus#77]
Thanks @ababic for making this package open-source. In the meantime I have over 10 different copy-pasted menu snippet in my projects, so decided to use this package instead!

While adding the main menu is notice the `seo_title` isn't displayed in my custom menu template.

```html
<ul class="main__menu">
    {% for menu_item in menu_items %}
    <li>
        <a href="{{ menu_item.href }}">{{ menu_item.text }}</a>
    </li>
    {% endfor %}
</ul>
```

My homepage has for example the title `website.com` (as it's the site's root page). The `seo_title` of the homepage is `Home` (as I don't want to display `website.com` as my menu item).

I expected `Home` was returned when using `menu_item.text` in the upper snippet. Wagtail does use this `seo_title` as well to override the title attribute.

Does this make sense, of is there a strong reason why `seo_title` is not taken instead?

**Comment by ababic** [comment]
Thanks @robmoorman. I hope it makes you're life a little easier.This project came out of a very familiar pain.

I can't say using `seo_title` as menu text is something I've ever thought about until you mentioned it here. If I had to come up with a reason for preferring `title` over `seo_title`, it would be that, in my experience, seo titles are more likely to be changed and tweaked over a pages life-span, which could be bad fit. I feel like editors generally concerned with SEO should be free to tweak a page's meta data without significantly effecting the user's experience.

But, all of that may be beside the point. Each menu item is either a `MenuItem` object or a `Page` object, in which case, it's possible to access the page and output any field you like. `href` and `text` are simply attributes that get added for consistency.

I feel like the best option for you here, though, would be just to add 'Home' as the `link_text` value on the menu item linking to that page. `link_text` on a `MenuItem` is preferred over the page's `title` value if it is defined.

Does this help you?

**Comment by robmoorman** [comment]
Thanks! I noticed the link_text and used that for now. I agree with the changes over time and SEO specialists better be not changing critical UX components like menu's.
