### ISSUE TITLE
Migration appearing when running makemigrations

### ISSUE THREAD

**Issue by urlsangel** [rkhleics/wagtailmenus#85]
Hi rkhleics

This migration keeps being referenced but not applied when running `makemigrations`:

```
Migrations for 'wagtailmenus':
  /usr/local/lib/python3.5/site-packages/wagtailmenus/migrations/0018_auto_20161208_0809.py:
    - Alter field site on mainmenu
```

Any idea what might be the cause?

Thanks,

Russell.

**Comment by ababic** [comment]
Hi @urlsangel. Thanks for raising this issue. Could you let me know which version of wagtailmenus you're using?

**Comment by urlsangel** [comment]
Sure thing, latest I think:

`wagtailmenus==2.0.1`

**Comment by ababic** [comment]
Hi @urlsangel The migration was added in a recent pull request, and I think only exists to cater for `verbose_name` additions to fields, so it shouldn't effect functionality:

https://github.com/rkhleics/wagtailmenus/commit/aac81ba4f67d15c9e1ed9b238e9b4cf88697b943

I've not really got any idea why it wouldn't be applied. Anybody else have any ideas?

**Comment by urlsangel** [comment]
I think it might not be in the pypi build - i'm running through Docker, and this is what the `ls` of the migrations folder looks like:

```
0001_initial.py
0002_auto_20160129_0901.py
0003_auto_20160129_2339.py
0004_auto_20160130_0024.py
0005_auto_20160130_2209.py
0006_auto_20160131_1347.py
0007_auto_20160131_2000.py
0008_auto_20160131_2327.py
0009_auto_20160201_0859.py
0010_auto_20160201_1558.py
0011_auto_20160415_1519.py
0012_auto_20160419_0039.py
0013_auto_20160423_1124.py
0014_auto_20160423_1339.py
0015_auto_20160423_1348.py
0016_auto_20160930_0645.py
0017_auto_20161013_1658.py
__init__.py
__pycache__
```

So looks like the updated field might be in the build, but not the migration maybe?

**Comment by ababic** [comment]
Thanks @urlsangel. Just looked at the dist package created by setuptools, and it seems the migration is missing. I'll see if repackaging will solve the issue.

**Comment by urlsangel** [comment]
Nice one, sounds like mystery solved 👍

**Comment by ababic** [comment]
Ah, wait. I think I see what the problem is. That particular migration referenced above (from p/r #83) isn't in an official release yet, and so shouldn't be in the distribution files. But, I think there's a change to the `site` field on `MainMenu` that isn't catered for anywhere yet.

**Comment by urlsangel** [comment]
So it's trying to recreate that migration each time?

**Comment by ababic** [comment]
@urlsangel Yeah, when you're running `makemigrations`, your system is creating that migration. 

Have just pushed a new version `2.0.2`, could you try pip installing that instead, and see if it fixes the issue on your machine?

**Comment by urlsangel** [comment]
Will do, I'll give that a go and report back.

**Comment by ababic** [comment]
@urlsangel apologies. just realised `2.0.2` is broken (that'll teach me not to run tests!). Try `wagtailmenus==2.0.3` instead :)

**Comment by urlsangel** [comment]
@ababic Pulled and rebuilt, all looking good.

Thanks for jumping on this so quickly 👍

**Comment by ababic** [comment]
Excellent. Thank you for bringing this to my attention, and happy developing :)

**Comment by clintonb** [comment]
I'm not sure if it's related, but I see the following error when attempting to run migrations for `2.0.3`:

> CommandError: Conflicting migrations detected; multiple leaf nodes in the migration graph: (0016_auto_20160721_0553, 0017_auto_20161013_1658 in wagtailmenus).
To fix them run 'python manage.py makemigrations --merge'

Please advise.

**Comment by clintonb** [comment]
I see the issue. There are two 0016 migrations.

**Comment by ababic** [comment]
Hi @clintonb. I'm not sure why you're seeing two 0016 migrations. There aren't two in the distributed version or on the `stable/2.0.x` branch used to create it. I'm afraid I don't really know what to suggest.

**Comment by clintonb** [comment]
@ababic thanks for the quick response. I'm not sure how the extra migration ended up there; but, uninstalling via `pip`, removing the site package, and reinstalling resolved the issue. False alarm.
