### ISSUE TITLE
Upgrading wagtail

### ISSUE THREAD

**Issue by adriaant** [rkhleics/wagtailmenus#91]
Wagtailmenus has a hard requirement on wagtail, so upgrading wagtail is not so trivial, since an install of wagtailmenus will revert the wagtail version. Would it not be better to leave wagtail out of the requirements and leave it to users to determine if the versions are compatible?

**Comment by ababic** [comment]
Hi @adriaant. That's a fair point, and worth implementing, I think. If I make it clear in the README what versions are officially supported, that should be enough for people to go on.

**Comment by ababic** [comment]
I have a PR to work on around adding official support for wagtail 1.8, so I'll likely take care of this along with that work.
