### ISSUE TITLE
section_menu tag throws error with modify_submenu_items

### ISSUE THREAD

**Issue by bmihelac** [rkhleics/wagtailmenus#98]
When `modify_submenu_items` returns list of `dict` items, `section_menu` tag  throws an error.
`section_menu` tries to access modified submenu item as object attribute in line:

https://github.com/rkhleics/wagtailmenus/blob/01ab3aa6a055128b50368e8047ffb51c4723b680/wagtailmenus/templatetags/menu_tags.py#L368

Workaround is to use `object` instead of `dict`.

**Comment by bmihelac** [comment]
Pull requests updates documentation to use `object` instead of `dict`:

https://github.com/rkhleics/wagtailmenus/pull/97

**Comment by ababic** [comment]
Hey there @bmihelac!

Thanks for raising this. Guiding people down the route of returning `MenuItem` objects is a good call, I think. But, I don't think that alone fixes the problem.

1. If the [`MenuItem`](/master/wagtailmenus/models/menuitems.py#L21) class is to be used in such a way, I think the class itself could do with some work to help guide it's use / add a basic level of validation. At the moment it's very bare, and potentially not fit for as many uses as it could be.

2. The [code in the section menu tag that triggers this error ](/wagtailmenus/blob/01ab3aa6a055128b50368e8047ffb51c4723b680/wagtailmenus/templatetags/menu_tags.py#L368) probably needs some further work to determine whether that action should be taking place. The code presumes that the first item is going to be the 'Repeated menu item', but if you're modifying the menu items further, there's no way to guarantee that. It would seem like there needs to be some sort of additional flag/attribute that we can look for on that first item to check if it really is the 'Repeated menu item', and should have the class added to it. Potentially, we might even need to cycle through all those children and do the same check too, as it might not always be the first item.

Any thoughts?

**Comment by ababic** [comment]
For now, I think I'd rather just wrap that code in a try/except block to capture an `AttributeError`. That would at least get around the issue without having to make existing users think about redeveloping how they are currently overriding the `MenuPage` methods.

**Comment by bmihelac** [comment]
To be honest, I did not read what code that has raised exception do as I had noticed fast enough that it is because of *dict item* vs *object attribute*.

Quick searching code showed that there is just one such case because (as I think) all other handlings of menu items are done in the templates where *dict item* vs *object attribute* is not important.

Because there could be other uses of menu items outside templates I thought it would be better to have just one way, rather than handling conversions.

**Comment by ababic** [comment]
You're right, I think that is the only place where being an object with attributes VS a dictionary is really a blocker. With that in mind, I do think the correct fix for now is to just wrap the code in a try/except, and also add something to that area of the documentation that says something along the lines of...

> If you're overriding `modify_submenu_items()`, make sure the 'repeated menu item' is still added as the first item in the returned list, otherwise active class highlighting might not work properly.

I will make these changes myself soon :)

**Comment by bmihelac** [comment]
OK, for the record, I did not use 'repeated menu item', this error occurs when using `section_menu` templatetag and `modify_submenu_items` as described in README.

**Comment by ababic** [comment]
Understood @bmihelac :) Thanks.
